"""C++ code generator."""

from typing import Any

from ..base import LanguageGenerator
from ...models import (
    Language,
    IntegrationMethod,
    GeneratedProject,
    CompiledModelInfo,
    BlockInfo,
)
from ...integration import IntegrationCodeGenerator
from .blocks import get_block_template, BLOCK_TEMPLATES


class CppCodeGenerator(LanguageGenerator):
    """Generate C++ simulation code."""

    def generate(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> GeneratedProject:
        """Generate a complete C++ project."""
        project = GeneratedProject(
            name=config.project_name,
            language=Language.CPP,
        )

        # Generate header files
        project.add_file("include/blocks.hpp", self._generate_blocks_header(model_info))
        project.add_file("include/simulation.hpp", self._generate_simulation_header(model_info))
        project.add_file("include/integration.hpp", IntegrationCodeGenerator.generate_cpp_header())

        # Generate source files
        project.add_file("src/blocks.cpp", self._generate_blocks_source(model_info))
        project.add_file("src/simulation.cpp", self._generate_simulation_source(model_info, config))
        project.add_file("src/integration.cpp", IntegrationCodeGenerator.generate_cpp_source())

        # Generate main.cpp
        if config.include_main:
            project.add_file("src/main.cpp", self.generate_main_code(model_info, config))

        # Generate build files
        project.add_file("CMakeLists.txt", self._generate_cmake(config))
        project.add_file("README.md", self._generate_readme(model_info, config))

        # Generate Dockerfile and build script
        project.add_file("Dockerfile", self._generate_dockerfile(config))
        project.add_file("build.sh", self._generate_build_script(config))

        return project

    def generate_block_code(self, block: BlockInfo) -> str:
        """Generate code for a single block."""
        template = get_block_template(block.type)
        class_name = f"Block_{self.sanitize_identifier(block.id)}"

        if template is None:
            return self._generate_passthrough_block(block, class_name)

        return template(block, class_name)

    def generate_integration_code(self, method: IntegrationMethod) -> str:
        """Generate integration method code."""
        return IntegrationCodeGenerator.generate_cpp_source()

    def generate_main_code(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate main entry point code."""
        csv_code = ""
        if config.include_csv_output:
            csv_code = '''
    // Write results to CSV
    std::ofstream csv("results.csv");
    if (csv) {
        csv << "time";
        for (int i = 0; i < n_outputs; i++) {
            csv << ",output" << i;
        }
        csv << "\\n";

        for (int i = 0; i < n_samples; i++) {
            csv << time_data[i];
            for (int j = 0; j < n_outputs; j++) {
                csv << "," << output_data[i * n_outputs + j];
            }
            csv << "\\n";
        }
        csv.close();
        std::cout << "Results written to results.csv" << std::endl;
    }
'''

        return f'''/**
 * Example simulation runner.
 * Generated by LibreSim Coder.
 */

#include <iostream>
#include <fstream>
#include <vector>
#include <cmath>
#include "simulation.hpp"
#include "integration.hpp"

int main() {{
    Model model;
    model.init();

    double t = {config.start_time};
    double dt = {config.step_size};
    double t_end = {config.stop_time};

    // Allocate output storage
    int n_samples = static_cast<int>((t_end - t) / dt) + 2;
    int n_outputs = 1;  // Adjust based on model outputs
    std::vector<double> time_data(n_samples);
    std::vector<double> output_data(n_samples * n_outputs);
    int sample_idx = 0;

    std::cout << "Running simulation..." << std::endl;

    // Get integration parameters
    int num_passes = get_num_passes("{config.integration_method.value}");

    while (t <= t_end) {{
        // Record data
        if (sample_idx < n_samples) {{
            time_data[sample_idx] = t;
            // Record first output (customize as needed)
            output_data[sample_idx] = model.get_output(0);
            sample_idx++;
        }}

        // Integration passes
        for (int kpass = 0; kpass < num_passes; kpass++) {{
            model.step(t, dt, kpass);
            model.propagate_integrators(dt, kpass, "{config.integration_method.value}");
        }}

        t += dt;
    }}

    std::cout << "Simulation complete. " << sample_idx << " samples." << std::endl;
{csv_code}
    return 0;
}}
'''

    def _generate_blocks_header(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.hpp with all block class definitions."""
        includes = '''/**
 * Block definitions.
 * Generated by LibreSim Coder.
 */

#ifndef BLOCKS_HPP
#define BLOCKS_HPP

#include <cmath>
#include <array>
#include <string>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

'''
        # Generate class declarations for each block
        classes = []
        for block in model_info.blocks:
            class_code = self.generate_block_code(block)
            classes.append(class_code)

        footer = "\n#endif // BLOCKS_HPP\n"
        return includes + "\n".join(classes) + footer

    def _generate_blocks_source(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.cpp (implementations are in header for simplicity)."""
        return '''/**
 * Block implementations.
 * Generated by LibreSim Coder.
 *
 * Note: Block implementations are inline in blocks.hpp for simplicity.
 */

#include "blocks.hpp"
'''

    def _generate_simulation_header(self, model_info: CompiledModelInfo) -> str:
        """Generate simulation.hpp with Model class and function declarations."""
        # Build block member declarations
        block_members = []
        for block in model_info.blocks:
            class_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            block_members.append(f"    {class_name} {var_name};")

        return f'''/**
 * Simulation model definition.
 * Generated by LibreSim Coder.
 */

#ifndef SIMULATION_HPP
#define SIMULATION_HPP

#include "blocks.hpp"
#include <string>

/**
 * Model containing all simulation blocks.
 */
class Model {{
public:
    double time = 0.0;
{chr(10).join(block_members)}

    /**
     * Initialize the model.
     */
    void init();

    /**
     * Execute one simulation step.
     *
     * @param t Current simulation time
     * @param dt Time step
     * @param kpass Integration pass number (0 to num_passes-1)
     */
    void step(double t, double dt, int kpass);

    /**
     * Wire block connections (update inputs from outputs).
     */
    void wire_connections();

    /**
     * Get model output.
     *
     * @param port Output port index
     * @return Output value
     */
    double get_output(int port) const;

    /**
     * Propagate integrators using specified method.
     */
    void propagate_integrators(double dt, int kpass, const std::string& method);
}};

#endif // SIMULATION_HPP
'''

    def _generate_simulation_source(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate simulation.cpp with Model implementation."""
        # Build initialization calls
        init_calls = []
        for block in model_info.blocks:
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            init_calls.append(f"    {var_name}.init();")

        # Build update calls in execution order
        update_calls = []
        for block_id in model_info.execution_order:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block:
                var_name = f"block_{self.sanitize_identifier(block.id)}"
                update_calls.append(f"    {var_name}.update(t);")

        # Build connection wiring
        connection_code = self._generate_connection_code(model_info)

        # Build output getter (use first sink block if available)
        output_code = "    return 0.0;"
        if model_info.sink_blocks:
            first_sink_id = model_info.sink_blocks[0]
            sink_block = next((b for b in model_info.blocks if b.id == first_sink_id), None)
            if sink_block:
                var_name = f"block_{self.sanitize_identifier(sink_block.id)}"
                output_code = f"    return {var_name}.get_output(port);"

        # Build integrator propagation
        integrator_code = self._generate_integrator_propagation(model_info)

        return f'''/**
 * Simulation model implementation.
 * Generated by LibreSim Coder.
 */

#include "simulation.hpp"
#include "integration.hpp"

void Model::init() {{
    time = 0.0;
{chr(10).join(init_calls)}
}}

void Model::wire_connections() {{
{connection_code}
}}

void Model::step(double t, double dt, int kpass) {{
    (void)dt;
    (void)kpass;
    time = t;

    // Wire connections
    wire_connections();

    // Update all blocks in execution order
{chr(10).join(update_calls)}
}}

double Model::get_output(int port) const {{
{output_code}
}}

void Model::propagate_integrators(double dt, int kpass, const std::string& method) {{
{integrator_code}
}}
'''

    def _generate_connection_code(self, model_info: CompiledModelInfo) -> str:
        """Generate connection wiring code."""
        lines = []
        for block in model_info.blocks:
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            for conn in block.input_connections:
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next(
                    (b for b in model_info.blocks if b.id == source_id), None
                )
                if source_block:
                    source_var = f"block_{self.sanitize_identifier(source_block.id)}"
                    if target_port is not None and target_port > 0:
                        lines.append(
                            f"    {var_name}.input{target_port} = "
                            f"{source_var}.get_output({source_port});"
                        )
                    else:
                        lines.append(
                            f"    {var_name}.input = "
                            f"{source_var}.get_output({source_port});"
                        )

        return "\n".join(lines) if lines else "    // No connections"

    def _generate_integrator_propagation(self, model_info: CompiledModelInfo) -> str:
        """Generate integrator propagation code for RK methods."""
        lines = []
        for block_id in model_info.integrator_blocks:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block and block.type == "integrator":
                var_name = f"block_{self.sanitize_identifier(block.id)}"
                lines.append(f'''    // Integrator: {block.name}
    propagate_integrator(
        {var_name}.state,
        {var_name}.xd0, {var_name}.xd1, {var_name}.xd2, {var_name}.xd3,
        {var_name}.get_derivative(),
        dt, kpass, method
    );''')

        return "\n".join(lines) if lines else "    // No integrators to propagate"

    def _generate_passthrough_block(self, block: BlockInfo, class_name: str) -> str:
        """Generate a passthrough block for unsupported types."""
        return f"""
// {block.name} - Passthrough (type: {block.type})
class {class_name} {{
public:
    double input = 0.0;
    double output = 0.0;

    void init() {{
        input = 0.0;
        output = 0.0;
    }}

    void update(double t) {{
        (void)t;
        output = input;
    }}

    double get_output(int port) const {{
        (void)port;
        return output;
    }}
}};
"""

    def _generate_cmake(self, config: Any) -> str:
        """Generate CMakeLists.txt."""
        return f'''cmake_minimum_required(VERSION 3.10)
project({config.project_name} CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Compiler warnings
if(MSVC)
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra -pedantic)
endif()

# Include directories
include_directories(include)

# Source files
set(SOURCES
    src/main.cpp
    src/simulation.cpp
    src/blocks.cpp
    src/integration.cpp
)

# Executable
add_executable(simulation ${{SOURCES}})

# Link math library on Unix
if(UNIX)
    target_link_libraries(simulation m)
endif()
'''

    def _generate_readme(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate README.md."""
        return f'''# {config.project_name}

C++ simulation generated by LibreSim Coder.

## Quick Start

```bash
# Create build directory
mkdir build && cd build

# Configure with CMake
cmake ..

# Build
make

# Run
./simulation
```

## Model Information

- **Blocks**: {len(model_info.blocks)}
- **Integration Method**: {config.integration_method.value}
- **Step Size**: {config.step_size}
- **Duration**: {config.start_time} to {config.stop_time} seconds

## Files

- `include/simulation.hpp` - Model class and declarations
- `include/blocks.hpp` - Block class definitions
- `include/integration.hpp` - Numerical integration methods
- `src/simulation.cpp` - Model implementation
- `src/blocks.cpp` - Block implementations
- `src/integration.cpp` - Integration implementation
- `src/main.cpp` - Example runner (outputs to results.csv)

## Customization

To modify simulation parameters, edit the constants in `main.cpp`:

```cpp
double t = {config.start_time};      // Start time
double dt = {config.step_size};      // Step size
double t_end = {config.stop_time};   // End time
```

## Docker Build

To create a standalone executable using Docker:

```bash
# Build using the provided script
./build.sh

# Or manually:
docker build -t {config.project_name}-builder .
docker run --rm -v $(pwd)/output:/output {config.project_name}-builder
```

The executable will be created in the `output/` directory.
'''

    def _generate_dockerfile(self, config: Any) -> str:
        """Generate Dockerfile for compilation."""
        return f'''# Dockerfile for compiling {config.project_name}
# Generated by LibreSim Coder

FROM gcc:13-bookworm

LABEL maintainer="LibreSim Coder"
LABEL description="Build environment for {config.project_name}"

# Install build tools
RUN apt-get update && apt-get install -y \\
    cmake \\
    make \\
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /build

# Copy project files
COPY . /build/

# Build the project
RUN mkdir -p build && cd build && \\
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 && \\
    make -j$(nproc)

# Create output directory and copy executable
RUN mkdir -p /output && cp build/simulation /output/

# Default command copies the executable to mounted output
CMD ["cp", "/output/simulation", "/output/"]
'''

    def _generate_build_script(self, config: Any) -> str:
        """Generate build script."""
        return f'''#!/bin/bash
# Build script for {config.project_name}
# Generated by LibreSim Coder

set -e

PROJECT_NAME="{config.project_name}"
IMAGE_NAME="${{PROJECT_NAME}}-builder"

echo "=== Building $PROJECT_NAME (C++) ==="

# Create output directory
mkdir -p output

# Build Docker image
echo "Building Docker image..."
docker build -t "$IMAGE_NAME" .

# Run container to compile
echo "Compiling..."
docker run --rm -v "$(pwd)/output:/output" "$IMAGE_NAME"

echo "=== Build Complete ==="
echo "Executable: output/simulation"
ls -la output/
'''
