"""C code generator."""

from typing import Any

from ..base import LanguageGenerator
from ...models import (
    Language,
    IntegrationMethod,
    GeneratedProject,
    CompiledModelInfo,
    BlockInfo,
)
from ...integration import IntegrationCodeGenerator
from .blocks import get_block_template, BLOCK_TEMPLATES


class CCodeGenerator(LanguageGenerator):
    """Generate C simulation code."""

    def generate(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> GeneratedProject:
        """Generate a complete C project."""
        project = GeneratedProject(
            name=config.project_name,
            language=Language.C,
        )

        # Generate header files
        project.add_file("include/blocks.h", self._generate_blocks_header(model_info))
        project.add_file("include/simulation.h", self._generate_simulation_header(model_info))
        project.add_file("include/integration.h", IntegrationCodeGenerator.generate_c_header())

        # Generate source files
        project.add_file("src/blocks.c", self._generate_blocks_source(model_info))
        project.add_file("src/simulation.c", self._generate_simulation_source(model_info, config))
        project.add_file("src/integration.c", IntegrationCodeGenerator.generate_c_source())

        # Generate main.c
        if config.include_main:
            project.add_file("src/main.c", self.generate_main_code(model_info, config))

        # Generate build files
        project.add_file("CMakeLists.txt", self._generate_cmake(config))
        project.add_file("README.md", self._generate_readme(model_info, config))

        return project

    def generate_block_code(self, block: BlockInfo) -> str:
        """Generate code for a single block."""
        template = get_block_template(block.type)
        struct_name = f"Block_{self.sanitize_identifier(block.id)}"

        if template is None:
            return self._generate_passthrough_block(block, struct_name)

        return template(block, struct_name)

    def generate_integration_code(self, method: IntegrationMethod) -> str:
        """Generate integration method code."""
        return IntegrationCodeGenerator.generate_c_source()

    def generate_main_code(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate main entry point code."""
        csv_code = ""
        if config.include_csv_output:
            csv_code = '''
    // Write results to CSV
    FILE* csv = fopen("results.csv", "w");
    if (csv) {
        fprintf(csv, "time");
        for (int i = 0; i < n_outputs; i++) {
            fprintf(csv, ",output%d", i);
        }
        fprintf(csv, "\\n");

        for (int i = 0; i < n_samples; i++) {
            fprintf(csv, "%g", time_data[i]);
            for (int j = 0; j < n_outputs; j++) {
                fprintf(csv, ",%g", output_data[i * n_outputs + j]);
            }
            fprintf(csv, "\\n");
        }
        fclose(csv);
        printf("Results written to results.csv\\n");
    }
'''

        return f'''/**
 * Example simulation runner.
 * Generated by LibreSim Coder.
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "simulation.h"
#include "integration.h"

int main(void) {{
    Model model;
    model_init(&model);

    double t = {config.start_time};
    double dt = {config.step_size};
    double t_end = {config.stop_time};

    // Allocate output storage
    int n_samples = (int)((t_end - t) / dt) + 2;
    int n_outputs = 1;  // Adjust based on model outputs
    double* time_data = (double*)malloc(n_samples * sizeof(double));
    double* output_data = (double*)malloc(n_samples * n_outputs * sizeof(double));
    int sample_idx = 0;

    printf("Running simulation...\\n");

    // Get integration parameters
    int num_passes = get_num_passes("{config.integration_method.value}");

    while (t <= t_end) {{
        // Record data
        if (sample_idx < n_samples) {{
            time_data[sample_idx] = t;
            // Record first output (customize as needed)
            output_data[sample_idx] = model_get_output(&model, 0);
            sample_idx++;
        }}

        // Integration passes
        for (int kpass = 0; kpass < num_passes; kpass++) {{
            model_step(&model, t, dt, kpass);
            propagate_integrators(&model, dt, kpass, "{config.integration_method.value}");
        }}

        t += dt;
    }}

    printf("Simulation complete. %d samples.\\n", sample_idx);
{csv_code}
    // Cleanup
    free(time_data);
    free(output_data);

    return 0;
}}
'''

    def _generate_blocks_header(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.h with all block struct definitions."""
        includes = '''/**
 * Block definitions.
 * Generated by LibreSim Coder.
 */

#ifndef BLOCKS_H
#define BLOCKS_H

#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

'''
        # Generate struct declarations for each block
        structs = []
        for block in model_info.blocks:
            struct_code = self.generate_block_code(block)
            structs.append(struct_code)

        footer = "\n#endif // BLOCKS_H\n"
        return includes + "\n".join(structs) + footer

    def _generate_blocks_source(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.c (implementations are in header for simplicity)."""
        return '''/**
 * Block implementations.
 * Generated by LibreSim Coder.
 *
 * Note: Block implementations are inline in blocks.h for simplicity.
 */

#include "blocks.h"
'''

    def _generate_simulation_header(self, model_info: CompiledModelInfo) -> str:
        """Generate simulation.h with Model struct and function declarations."""
        # Build block member declarations
        block_members = []
        for block in model_info.blocks:
            struct_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            block_members.append(f"    {struct_name} {var_name};")

        return f'''/**
 * Simulation model definition.
 * Generated by LibreSim Coder.
 */

#ifndef SIMULATION_H
#define SIMULATION_H

#include "blocks.h"

/**
 * Model containing all simulation blocks.
 */
typedef struct {{
    double time;
{chr(10).join(block_members)}
}} Model;

/**
 * Initialize the model.
 */
void model_init(Model* model);

/**
 * Execute one simulation step.
 *
 * @param model Model instance
 * @param t Current simulation time
 * @param dt Time step
 * @param kpass Integration pass number (0 to num_passes-1)
 */
void model_step(Model* model, double t, double dt, int kpass);

/**
 * Wire block connections (update inputs from outputs).
 */
void model_wire_connections(Model* model);

/**
 * Get model output.
 *
 * @param model Model instance
 * @param port Output port index
 * @return Output value
 */
double model_get_output(Model* model, int port);

#endif // SIMULATION_H
'''

    def _generate_simulation_source(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate simulation.c with Model implementation."""
        # Build initialization calls
        init_calls = []
        for block in model_info.blocks:
            struct_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            init_calls.append(f"    {struct_name}_init(&model->{var_name});")

        # Build update calls in execution order
        update_calls = []
        for block_id in model_info.execution_order:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block:
                struct_name = f"Block_{self.sanitize_identifier(block.id)}"
                var_name = f"block_{self.sanitize_identifier(block.id)}"
                update_calls.append(f"    {struct_name}_update(&model->{var_name}, t);")

        # Build connection wiring
        connection_code = self._generate_connection_code(model_info)

        # Build output getter (use first sink block if available)
        output_code = "    return 0.0;"
        if model_info.sink_blocks:
            first_sink_id = model_info.sink_blocks[0]
            sink_block = next((b for b in model_info.blocks if b.id == first_sink_id), None)
            if sink_block:
                struct_name = f"Block_{self.sanitize_identifier(sink_block.id)}"
                var_name = f"block_{self.sanitize_identifier(sink_block.id)}"
                output_code = f"    return {struct_name}_get_output(&model->{var_name}, port);"

        return f'''/**
 * Simulation model implementation.
 * Generated by LibreSim Coder.
 */

#include "simulation.h"

void model_init(Model* model) {{
    model->time = 0.0;
{chr(10).join(init_calls)}
}}

void model_wire_connections(Model* model) {{
{connection_code}
}}

void model_step(Model* model, double t, double dt, int kpass) {{
    (void)dt;
    (void)kpass;
    model->time = t;

    // Wire connections
    model_wire_connections(model);

    // Update all blocks in execution order
{chr(10).join(update_calls)}
}}

double model_get_output(Model* model, int port) {{
{output_code}
}}
'''

    def _generate_connection_code(self, model_info: CompiledModelInfo) -> str:
        """Generate connection wiring code."""
        lines = []
        for block in model_info.blocks:
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            for conn in block.input_connections:
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next(
                    (b for b in model_info.blocks if b.id == source_id), None
                )
                if source_block:
                    source_struct = f"Block_{self.sanitize_identifier(source_block.id)}"
                    source_var = f"block_{self.sanitize_identifier(source_block.id)}"
                    if target_port is not None and target_port > 0:
                        lines.append(
                            f"    model->{var_name}.input{target_port} = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )
                    else:
                        lines.append(
                            f"    model->{var_name}.input = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )

        return "\n".join(lines) if lines else "    // No connections"

    def _generate_passthrough_block(self, block: BlockInfo, struct_name: str) -> str:
        """Generate a passthrough block for unsupported types."""
        return f"""
// {block.name} - Passthrough (type: {block.type})
typedef struct {{
    double input;
    double output;
}} {struct_name};

void {struct_name}_init({struct_name}* b) {{
    b->input = 0.0;
    b->output = 0.0;
}}

void {struct_name}_update({struct_name}* b, double t) {{
    (void)t;
    b->output = b->input;
}}

double {struct_name}_get_output({struct_name}* b, int port) {{
    (void)port;
    return b->output;
}}
"""

    def _generate_cmake(self, config: Any) -> str:
        """Generate CMakeLists.txt."""
        return f'''cmake_minimum_required(VERSION 3.10)
project({config.project_name} C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

# Compiler warnings
if(MSVC)
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra -pedantic)
endif()

# Include directories
include_directories(include)

# Source files
set(SOURCES
    src/main.c
    src/simulation.c
    src/blocks.c
    src/integration.c
)

# Executable
add_executable(simulation ${{SOURCES}})

# Link math library on Unix
if(UNIX)
    target_link_libraries(simulation m)
endif()
'''

    def _generate_readme(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate README.md."""
        return f'''# {config.project_name}

C simulation generated by LibreSim Coder.

## Quick Start

```bash
# Create build directory
mkdir build && cd build

# Configure with CMake
cmake ..

# Build
make

# Run
./simulation
```

## Model Information

- **Blocks**: {len(model_info.blocks)}
- **Integration Method**: {config.integration_method.value}
- **Step Size**: {config.step_size}
- **Duration**: {config.start_time} to {config.stop_time} seconds

## Files

- `include/simulation.h` - Model struct and function declarations
- `include/blocks.h` - Block struct definitions
- `include/integration.h` - Numerical integration methods
- `src/simulation.c` - Model implementation
- `src/blocks.c` - Block implementations
- `src/integration.c` - Integration implementation
- `src/main.c` - Example runner (outputs to results.csv)

## Customization

To modify simulation parameters, edit the constants in `main.c`:

```c
double t = {config.start_time};      // Start time
double dt = {config.step_size};      // Step size
double t_end = {config.stop_time};   // End time
```
'''
