"""C code generator."""

from typing import Any

from ...integration import IntegrationCodeGenerator
from ...models import (
    BlockInfo,
    CompiledModelInfo,
    GeneratedProject,
    IntegrationMethod,
    Language,
)
from ..base import LanguageGenerator
from .blocks import get_block_template


class CCodeGenerator(LanguageGenerator):
    """Generate C simulation code."""

    def generate(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> GeneratedProject:
        """Generate a complete C project."""
        project = GeneratedProject(
            name=config.project_name,
            language=Language.C,
        )

        # Generate header files
        project.add_file("include/blocks.h", self._generate_blocks_header(model_info))
        project.add_file("include/simulation.h", self._generate_simulation_header(model_info))
        project.add_file("include/integration.h", IntegrationCodeGenerator.generate_c_header())

        # Generate source files
        project.add_file("src/blocks.c", self._generate_blocks_source(model_info))
        project.add_file("src/simulation.c", self._generate_simulation_source(model_info, config))
        project.add_file("src/integration.c", IntegrationCodeGenerator.generate_c_source())

        # Generate main.c
        if config.include_main:
            project.add_file("src/main.c", self.generate_main_code(model_info, config))

        # Generate build files
        project.add_file("CMakeLists.txt", self._generate_cmake(config))
        project.add_file("README.md", self._generate_readme(model_info, config))

        # Generate Dockerfile and build/run scripts
        project.add_file("Dockerfile", self._generate_dockerfile(config))
        project.add_file("build.sh", self._generate_build_script(config))
        project.add_file("run.sh", self._generate_run_script(config))

        return project

    def generate_block_code(self, block: BlockInfo) -> str:
        """Generate code for a single block."""
        template = get_block_template(block.type)
        struct_name = f"Block_{self.sanitize_identifier(block.id)}"

        if template is None:
            return self._generate_passthrough_block(block, struct_name)

        return template(block, struct_name)

    def generate_integration_code(self, method: IntegrationMethod) -> str:
        """Generate integration method code."""
        return IntegrationCodeGenerator.generate_c_source()

    def _generate_output_recording(self, model_info: CompiledModelInfo) -> dict:
        """Generate output recording code from the shared canonical output schema."""
        output_names: list[str] = []
        record_code_lines: list[str] = []
        blocks = {block.id: block for block in model_info.blocks}

        for column, signal in enumerate(model_info.output_signals):
            source = blocks[signal.source_block_id]
            struct_name = f"Block_{self.sanitize_identifier(source.id)}"
            var_name = f"block_{self.sanitize_identifier(source.id)}"
            port = signal.flat_index if signal.dimensions[0] > 1 else signal.source_output_port
            output_names.append(signal.canonical_key)
            record_code_lines.append(
                f"            output_data[sample_idx * n_outputs + {column}] = "
                f"{struct_name}_get_output(&model.{var_name}, {port});"
            )

        return {
            "names": output_names,
            "n_outputs": len(output_names),
            "record_code": "\n".join(record_code_lines)
            if record_code_lines
            else "            // No outputs to record",
        }

    def generate_main_code(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate main entry point code."""
        # Get output recording info
        output_info = self._generate_output_recording(model_info)
        n_outputs = output_info["n_outputs"]
        output_names = output_info["names"]
        record_code = output_info["record_code"]

        # Build CSV header with column names
        csv_header_parts = ["time"] + output_names
        csv_header = ",".join(csv_header_parts)

        csv_code = ""
        if config.include_csv_output:
            csv_code = f"""
    // Write results to CSV
    FILE* csv = fopen("results.csv", "w");
    if (csv) {{
        fprintf(csv, "{csv_header}\\n");

        for (int i = 0; i < sample_idx; i++) {{
            fprintf(csv, "%g", time_data[i]);
            for (int j = 0; j < n_outputs; j++) {{
                fprintf(csv, ",%g", output_data[i * n_outputs + j]);
            }}
            fprintf(csv, "\\n");
        }}
        fclose(csv);
        printf("Results written to results.csv\\n");
    }}
"""

        return f"""/**
 * Example simulation runner.
 * Generated by LibreSim Coder.
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "simulation.h"
#include "integration.h"

int main(void) {{
    Model model;
    model_init(&model);

    double t = {config.start_time};
    double dt = {config.step_size};
    double t_end = {config.stop_time};

    // Allocate output storage
    int n_samples = (int)((t_end - t) / dt) + 2;
    int n_outputs = {n_outputs};  // Number of output signals
    double* time_data = (double*)malloc(n_samples * sizeof(double));
    double* output_data = (double*)malloc(n_samples * n_outputs * sizeof(double));
    int sample_idx = 0;

    printf("Running simulation...\\n");

    // Get integration parameters
    int num_passes = get_num_passes("{config.integration_method.value}");
    const double* stage_offsets = get_stage_offsets("{config.integration_method.value}");

    while (t <= t_end) {{
        // Major-step update: commit sampled state and establish recorded outputs.
        model_step(&model, t, dt, 0, 1);
        if (sample_idx < n_samples) {{
            time_data[sample_idx] = t;
{record_code}
            sample_idx++;
        }}

        // Integration passes
        for (int kpass = 0; kpass < num_passes; kpass++) {{
            model_step(&model, t + stage_offsets[kpass] * dt, dt, kpass, 0);

            model_propagate_integrators(&model, dt, kpass, "{config.integration_method.value}");
        }}

        t += dt;
    }}

    printf("Simulation complete. %d samples.\\n", sample_idx);
{csv_code}
    // Cleanup
    free(time_data);
    free(output_data);

    return 0;
}}
"""

    def _generate_blocks_header(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.h with all block struct definitions."""
        import re

        includes = """/**
 * Block definitions.
 * Generated by LibreSim Coder.
 */

#ifndef BLOCKS_H
#define BLOCKS_H

#include <math.h>
#include "integration.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

"""
        # Generate struct declarations for each block
        structs = []
        for block in model_info.blocks:
            struct_code = self.generate_block_code(block)
            structs.append(struct_code)

        combined = "\n".join(structs)

        # Make all function definitions static inline to avoid multiple definition errors
        # Pattern matches: return_type function_name(params) {
        # But not typedef struct or already static functions
        combined = re.sub(
            r"^(void|double|int|static double) (Block_\w+)\(",
            r"static inline \1 \2(",
            combined,
            flags=re.MULTILINE,
        )
        # Remove duplicate "static" if already present
        combined = combined.replace("static inline static", "static inline")

        footer = "\n#endif // BLOCKS_H\n"
        return includes + combined + footer

    def _generate_blocks_source(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.c (implementations are in header for simplicity)."""
        return """/**
 * Block implementations.
 * Generated by LibreSim Coder.
 *
 * Note: Block implementations are inline in blocks.h for simplicity.
 */

#include "blocks.h"
"""

    def _generate_simulation_header(self, model_info: CompiledModelInfo) -> str:
        """Generate simulation.h with Model struct and function declarations."""
        # Build block member declarations
        block_members = []
        for block in model_info.blocks:
            struct_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            block_members.append(f"    {struct_name} {var_name};")

        return f"""/**
 * Simulation model definition.
 * Generated by LibreSim Coder.
 */

#ifndef SIMULATION_H
#define SIMULATION_H

#include "blocks.h"

/**
 * Model containing all simulation blocks.
 */
typedef struct {{
    double time;
{chr(10).join(block_members)}
}} Model;

/**
 * Initialize the model.
 */
void model_init(Model* model);

/**
 * Execute one simulation step.
 *
 * @param model Model instance
 * @param t Current simulation time
 * @param dt Time step
 * @param kpass Integration pass number (0 to num_passes-1)
 */
void model_step(Model* model, double t, double dt, int kpass, int ready);

/**
 * Wire block connections (update inputs from outputs).
 */
void model_wire_connections(Model* model);

/**
 * Get model output.
 *
 * @param model Model instance
 * @param port Output port index
 * @return Output value
 */
double model_get_output(Model* model, int port);

/**
 * Propagate integrators using specified method.
 */
void model_propagate_integrators(Model* model, double dt, int kpass, const char* method);

#endif // SIMULATION_H
"""

    def _generate_simulation_source(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate simulation.c with Model implementation."""
        # Build initialization calls
        init_calls = []
        for block in model_info.blocks:
            struct_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            init_calls.append(f"    {struct_name}_init(&model->{var_name});")

        # Build per-block wiring for inline wiring during step
        block_wiring = self._generate_per_block_wiring(model_info)

        # Build update calls in execution order with inline wiring
        update_calls: list[str] = []
        for block_id in model_info.execution_order:
            block_match = next((b for b in model_info.blocks if b.id == block_id), None)
            if block_match is not None:
                struct_name = f"Block_{self.sanitize_identifier(block_match.id)}"
                var_name = f"block_{self.sanitize_identifier(block_match.id)}"
                # Add wiring for this block's inputs (if any)
                if block_id in block_wiring:
                    for wire_line in block_wiring[block_id]:
                        update_calls.append(wire_line)
                if block_match.ready_only:
                    update_calls.append(
                        f"    if (ready) {{ {struct_name}_update(&model->{var_name}, t); }}"
                    )
                elif block_match.type in {
                    "rate_limiter",
                    "madgwick_filter",
                    "complementary_filter",
                }:
                    update_calls.append(f"    {struct_name}_update(&model->{var_name}, t, dt);")
                else:
                    update_calls.append(f"    {struct_name}_update(&model->{var_name}, t);")

        # Build connection wiring (for wire_connections method - kept for compatibility)
        connection_code = self._generate_connection_code(model_info)

        # Build output getter (use first sink block if available)
        output_code = "    return 0.0;"
        if model_info.sink_blocks:
            first_sink_id = model_info.sink_blocks[0]
            sink_block = next((b for b in model_info.blocks if b.id == first_sink_id), None)
            if sink_block:
                struct_name = f"Block_{self.sanitize_identifier(sink_block.id)}"
                var_name = f"block_{self.sanitize_identifier(sink_block.id)}"
                output_code = f"    return {struct_name}_get_output(&model->{var_name}, port);"

        # Build integrator propagation
        integrator_code = self._generate_integrator_propagation(model_info)

        return f"""/**
 * Simulation model implementation.
 * Generated by LibreSim Coder.
 */

#include "simulation.h"
#include "integration.h"

void model_init(Model* model) {{
    model->time = 0.0;
{chr(10).join(init_calls)}
}}

void model_wire_connections(Model* model) {{
{connection_code}
}}

void model_step(Model* model, double t, double dt, int kpass, int ready) {{
    (void)dt;
    (void)kpass;
    model->time = t;

    // Update all blocks in execution order (with inline wiring)
{chr(10).join(update_calls)}
}}

double model_get_output(Model* model, int port) {{
{output_code}
}}

void model_propagate_integrators(Model* model, double dt, int kpass, const char* method) {{
{integrator_code}
}}
"""

    def _generate_per_block_wiring(self, model_info: CompiledModelInfo) -> dict:
        """Generate per-block wiring code for inline wiring during step.

        Returns:
            Dictionary mapping block_id to list of wiring code lines
        """
        wiring: dict[str, list[str]] = {}
        for block in model_info.blocks:
            f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            block_lines = []
            for conn in block.input_connections:
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next((b for b in model_info.blocks if b.id == source_id), None)
                if source_block:
                    source_struct = f"Block_{self.sanitize_identifier(source_block.id)}"
                    source_var = f"block_{self.sanitize_identifier(source_block.id)}"
                    port_idx = target_port if target_port is not None else 0

                    # Check if this is a vector-to-vector connection
                    source_is_vector = self._is_vector_output(source_block, source_port)
                    target_expects_vector = self._expects_vector_input(block, port_idx)

                    # Multi-input blocks use input0, input1, etc.
                    if block.type in self.MULTI_INPUT_BLOCKS:
                        block_lines.append(
                            f"    model->{var_name}.input{port_idx} = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )
                    elif source_is_vector and target_expects_vector:
                        # Vector-to-vector: use get_output_vector and memcpy
                        # Get vector size from source output dimensions
                        vec_size = 3  # default
                        if source_block.output_dimensions and source_port < len(
                            source_block.output_dimensions
                        ):
                            dims = source_block.output_dimensions[source_port]
                            if len(dims) > 0:
                                vec_size = dims[0]
                        input_field = "input" if port_idx == 0 else f"input{port_idx}"
                        # For demux outputs, use port-specific get_output_vector{n}
                        vector_suffix = "" if source_port == 0 else str(source_port)
                        block_lines.append(
                            f"    memcpy(model->{var_name}.{input_field}, "
                            f"{source_struct}_get_output_vector{vector_suffix}(&model->{source_var}), "
                            f"{vec_size} * sizeof(double));"
                        )
                    elif target_port is not None and target_port > 0:
                        block_lines.append(
                            f"    model->{var_name}.input{target_port} = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )
                    else:
                        block_lines.append(
                            f"    model->{var_name}.input = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )
            if block_lines:
                wiring[block.id] = block_lines
        return wiring

    # Block types that use indexed inputs (input0, input1, etc.)
    MULTI_INPUT_BLOCKS = {"sum", "product", "mux", "switch"}

    # Block types that output vectors and have get_output_vector function
    VECTOR_OUTPUT_BLOCKS = {"mux", "constant", "gain", "demux"}

    # Block types that expect vector inputs (not via indexed ports)
    VECTOR_INPUT_BLOCKS = {"demux", "gain"}

    def _is_vector_output(self, block: "BlockInfo", port: int = 0) -> bool:
        """Check if a block's output port produces a vector (not scalar)."""
        if block.output_dimensions and port < len(block.output_dimensions):
            dims = block.output_dimensions[port]
            if len(dims) > 0 and dims[0] > 1:
                return True
        if block.type in self.VECTOR_OUTPUT_BLOCKS:
            if block.type == "mux":
                return True
            if block.type == "constant":
                value = block.parameters.get("value", 0.0)
                return isinstance(value, (list, tuple))
        return False

    def _expects_vector_input(self, block: "BlockInfo", port: int = 0) -> bool:
        """Check if a block expects a vector input (not scalar) at given port."""
        if block.input_dimensions and port < len(block.input_dimensions):
            dims = block.input_dimensions[port]
            if len(dims) > 0 and dims[0] > 1:
                return True
        if block.type == "demux":
            return True
        return False

    def _generate_connection_code(self, model_info: CompiledModelInfo) -> str:
        """Generate connection wiring code."""
        lines = []
        for block in model_info.blocks:
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            for conn in block.input_connections:
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next((b for b in model_info.blocks if b.id == source_id), None)
                if source_block:
                    source_struct = f"Block_{self.sanitize_identifier(source_block.id)}"
                    source_var = f"block_{self.sanitize_identifier(source_block.id)}"
                    port_idx = target_port if target_port is not None else 0

                    # Check if this is a vector-to-vector connection
                    source_is_vector = self._is_vector_output(source_block, source_port)
                    target_expects_vector = self._expects_vector_input(block, port_idx)

                    # Multi-input blocks use input0, input1, etc.
                    if block.type in self.MULTI_INPUT_BLOCKS:
                        lines.append(
                            f"    model->{var_name}.input{port_idx} = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )
                    elif source_is_vector and target_expects_vector:
                        # Vector-to-vector: copy array elements
                        # In C we need to copy each element or use memcpy
                        # Get vector size from source output dimensions
                        vec_size = 3  # default
                        if source_block.output_dimensions and source_port < len(
                            source_block.output_dimensions
                        ):
                            dims = source_block.output_dimensions[source_port]
                            if len(dims) > 0:
                                vec_size = dims[0]
                        # For port 0 use 'input', for port 1+ use 'input1', 'input2', etc.
                        input_field = "input" if port_idx == 0 else f"input{port_idx}"
                        lines.append(
                            f"    memcpy(model->{var_name}.{input_field}, "
                            f"{source_struct}_get_output_vector(&model->{source_var}), "
                            f"{vec_size} * sizeof(double));"
                        )
                    elif target_port is not None and target_port > 0:
                        lines.append(
                            f"    model->{var_name}.input{target_port} = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )
                    else:
                        lines.append(
                            f"    model->{var_name}.input = "
                            f"{source_struct}_get_output(&model->{source_var}, {source_port});"
                        )

        return "\n".join(lines) if lines else "    // No connections"

    def _generate_integrator_propagation(self, model_info: CompiledModelInfo) -> str:
        """Generate integrator propagation code for RK methods."""
        lines = []
        integrator_ids = set(model_info.integrator_blocks)
        for block in model_info.blocks:
            if block.id in integrator_ids or block.custom_state_propagation:
                struct_name = f"Block_{self.sanitize_identifier(block.id)}"
                var_name = f"block_{self.sanitize_identifier(block.id)}"
                if block.type == "integrator":
                    lines.append(f"""    // Integrator: {block.name}
    propagate_integrator(
        &model->{var_name}.state,
        &model->{var_name}.x0, &model->{var_name}.xd0, &model->{var_name}.xd1,
        &model->{var_name}.xd2, &model->{var_name}.xd3,
        {struct_name}_get_derivative(&model->{var_name}),
        dt, kpass, method
    );""")
                elif block.custom_state_propagation:
                    lines.append(f"""    // {block.type}: {block.name}
    {struct_name}_propagate_states(&model->{var_name}, dt, kpass, method);""")

        return "\n".join(lines) if lines else "    // No integrators to propagate"

    def _generate_passthrough_block(self, block: BlockInfo, struct_name: str) -> str:
        """Generate a passthrough block for unsupported types."""
        # Determine number of inputs from connections
        num_inputs = 1
        for conn in block.input_connections:
            _, _, target_port = self.parse_connection(conn)
            if target_port is not None:
                num_inputs = max(num_inputs, target_port + 1)

        # Generate input declarations
        input_decls = []
        for i in range(num_inputs):
            if i == 0:
                input_decls.append("    double input;")
            else:
                input_decls.append(f"    double input{i};")
        input_decls_str = "\n".join(input_decls)

        return f"""
// {block.name} - Passthrough (type: {block.type})
typedef struct {{
{input_decls_str}
    double output;
}} {struct_name};

void {struct_name}_init({struct_name}* b) {{
    b->input = 0.0;
    b->output = 0.0;
}}

void {struct_name}_update({struct_name}* b, double t) {{
    (void)t;
    b->output = b->input;  // Uses first input as passthrough
}}

double {struct_name}_get_output({struct_name}* b, int port) {{
    (void)port;
    return b->output;
}}
"""

    def _generate_cmake(self, config: Any) -> str:
        """Generate CMakeLists.txt."""
        return f"""cmake_minimum_required(VERSION 3.10)
project({config.project_name} C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

# Compiler warnings
if(MSVC)
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra -pedantic)
endif()

# Include directories
include_directories(include)

# Source files
set(SOURCES
    src/main.c
    src/simulation.c
    src/blocks.c
    src/integration.c
)

# Executable
add_executable(simulation ${{SOURCES}})

# Link math library on Unix
if(UNIX)
    target_link_libraries(simulation m)
endif()
"""

    def _generate_readme(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate README.md."""
        return f"""# {config.project_name}

C simulation generated by LibreSim Coder.

## Quick Start

```bash
# Create build directory
mkdir build && cd build

# Configure with CMake
cmake ..

# Build
make

# Run
./simulation
```

## Model Information

- **Blocks**: {len(model_info.blocks)}
- **Integration Method**: {config.integration_method.value}
- **Step Size**: {config.step_size}
- **Duration**: {config.start_time} to {config.stop_time} seconds

## Files

- `include/simulation.h` - Model struct and function declarations
- `include/blocks.h` - Block struct definitions
- `include/integration.h` - Numerical integration methods
- `src/simulation.c` - Model implementation
- `src/blocks.c` - Block implementations
- `src/integration.c` - Integration implementation
- `src/main.c` - Example runner (outputs to results.csv)

## Customization

To modify simulation parameters, edit the constants in `main.c`:

```c
double t = {config.start_time};      // Start time
double dt = {config.step_size};      // Step size
double t_end = {config.stop_time};   // End time
```

## Docker Build

To create a standalone executable using Docker:

```bash
# Build using the provided script
./build.sh

# Or manually:
docker build -t {config.project_name}-builder .
docker run --rm -v $(pwd)/output:/output {config.project_name}-builder
```

The executable will be created in the `output/` directory.
"""

    def _generate_dockerfile(self, config: Any) -> str:
        """Generate Dockerfile for compilation and execution."""
        return f"""# Dockerfile for compiling and running {config.project_name}
# Generated by LibreSim Coder

FROM gcc:13-bookworm

LABEL maintainer="LibreSim Coder"
LABEL description="Build environment for {config.project_name}"

# Install build tools
RUN apt-get update && apt-get install -y \\
    cmake \\
    make \\
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /build

# Copy project files
COPY . /build/

# Make scripts executable
RUN chmod +x /build/run.sh

# Build the project
RUN mkdir -p build && cd build && \\
    cmake .. -DCMAKE_BUILD_TYPE=Release && \\
    make -j$(nproc)

# Default command runs the simulation and copies outputs
CMD ["/build/run.sh"]
"""

    def _generate_build_script(self, config: Any) -> str:
        """Generate build script."""
        return f"""#!/bin/bash
# Build and run script for {config.project_name}
# Generated by LibreSim Coder
#
# This script:
# 1. Builds a Docker image with the compiled simulation
# 2. Runs the simulation inside the container
# 3. Copies the executable and results to ./output/

set -e

PROJECT_NAME="{config.project_name}"
IMAGE_NAME="${{PROJECT_NAME}}-builder"

echo "=== Building and Running $PROJECT_NAME (C) ==="

# Create output directory
mkdir -p output

# Get absolute path (works on both Linux/Mac and Windows Git Bash)
if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ -n "$WINDIR" ]]; then
    # Windows: convert to Docker-compatible path
    OUTPUT_PATH="$(cd output && pwd -W 2>/dev/null || pwd)"
else
    OUTPUT_PATH="$(cd output && pwd)"
fi

# Build Docker image (compiles the code)
echo "[1/2] Building Docker image (compiling code)..."
docker build -t "$IMAGE_NAME" .

# Run container (executes simulation and copies outputs)
echo "[2/2] Running simulation..."
# MSYS_NO_PATHCONV prevents Git Bash from mangling the volume mount path
MSYS_NO_PATHCONV=1 docker run --rm -v "$OUTPUT_PATH:/output" "$IMAGE_NAME"

echo ""
echo "=== Complete ==="
echo "Output files:"
ls -la output/

# Show first/last few lines of results if CSV exists
if [ -f output/results.csv ]; then
    echo ""
    echo "=== Results Preview (first 5 lines) ==="
    head -n 5 output/results.csv
    echo "..."
    echo "=== Results Preview (last 5 lines) ==="
    tail -n 5 output/results.csv
fi
"""

    def _generate_run_script(self, config: Any) -> str:
        """Generate run script that executes inside Docker container."""
        return f"""#!/bin/bash
# Run script for {config.project_name}
# This script runs inside the Docker container
# Generated by LibreSim Coder

set -e

echo "Running simulation..."

# Run the simulation (generates results.csv in current directory)
cd /build/build
./simulation

echo ""
echo "Simulation complete."

# Copy outputs to mounted volume
if [ -d "/output" ]; then
    echo "Copying outputs to /output..."
    cp -f simulation /output/ 2>/dev/null || true
    cp -f results.csv /output/ 2>/dev/null || true
    echo "Done."
else
    echo "Warning: /output not mounted, results not copied."
fi
"""
