"""Rust code generator."""

from typing import Any

from ..base import LanguageGenerator
from ...models import (
    Language,
    IntegrationMethod,
    GeneratedProject,
    CompiledModelInfo,
    BlockInfo,
)
from ...integration import IntegrationCodeGenerator
from .blocks import get_block_template, BLOCK_TEMPLATES


class RustCodeGenerator(LanguageGenerator):
    """Generate Rust simulation code."""

    def generate(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> GeneratedProject:
        """Generate a complete Rust project."""
        project = GeneratedProject(
            name=config.project_name,
            language=Language.RUST,
        )

        # Generate source files
        project.add_file("src/lib.rs", self._generate_lib(model_info, config))
        project.add_file("src/blocks.rs", self._generate_blocks(model_info))
        project.add_file("src/integration.rs", IntegrationCodeGenerator.generate_rust())

        # Generate main.rs
        if config.include_main:
            project.add_file("src/main.rs", self.generate_main_code(model_info, config))

        # Generate build files
        project.add_file("Cargo.toml", self._generate_cargo(config))
        project.add_file("README.md", self._generate_readme(model_info, config))

        # Generate Dockerfile and build script
        project.add_file("Dockerfile", self._generate_dockerfile(config))
        project.add_file("build.sh", self._generate_build_script(config))

        return project

    def generate_block_code(self, block: BlockInfo) -> str:
        """Generate code for a single block."""
        template = get_block_template(block.type)
        struct_name = f"Block_{self.sanitize_identifier(block.id)}"

        if template is None:
            return self._generate_passthrough_block(block, struct_name)

        return template(block, struct_name)

    def generate_integration_code(self, method: IntegrationMethod) -> str:
        """Generate integration method code."""
        return IntegrationCodeGenerator.generate_rust()

    def generate_main_code(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate main entry point code."""
        project_name = config.project_name.replace('-', '_')

        csv_code = ""
        if config.include_csv_output:
            csv_code = '''
    // Write results to CSV
    let mut csv_file = std::fs::File::create("results.csv").expect("Could not create file");
    use std::io::Write;
    writeln!(csv_file, "time,output0").unwrap();
    for (t, y) in time_data.iter().zip(output_data.iter()) {
        writeln!(csv_file, "{},{}", t, y).unwrap();
    }
    println!("Results written to results.csv");
'''

        return f'''//! Example simulation runner
//! Generated by LibreSim Coder.

use {project_name}::Model;
use {project_name}::integration::{{IntegrationMethod, get_num_passes}};

fn main() {{
    let mut model = Model::new();
    model.init();

    let mut t = {config.start_time}_f64;
    let dt = {config.step_size}_f64;
    let t_end = {config.stop_time}_f64;

    // Allocate output storage
    let n_samples = ((t_end - t) / dt) as usize + 2;
    let mut time_data: Vec<f64> = Vec::with_capacity(n_samples);
    let mut output_data: Vec<f64> = Vec::with_capacity(n_samples);

    println!("Running simulation...");

    let method = IntegrationMethod::from_str("{config.integration_method.value}");
    let num_passes = get_num_passes(method);

    while t <= t_end {{
        // Record data
        time_data.push(t);
        output_data.push(model.get_output(0));

        // Integration passes
        for kpass in 0..num_passes {{
            model.step(t, dt, kpass);
            model.propagate_integrators(dt, kpass, method);
        }}

        t += dt;
    }}

    println!("Simulation complete. {{}} samples.", time_data.len());
{csv_code}
}}
'''

    def _generate_lib(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate lib.rs with Model struct."""
        # Build block member declarations
        block_members = []
        for block in model_info.blocks:
            struct_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            block_members.append(f"    pub {var_name}: blocks::{struct_name},")

        # Build initialization calls
        init_calls = []
        for block in model_info.blocks:
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            init_calls.append(f"        self.{var_name}.init();")

        # Build update calls in execution order
        update_calls = []
        for block_id in model_info.execution_order:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block:
                var_name = f"block_{self.sanitize_identifier(block.id)}"
                update_calls.append(f"        self.{var_name}.update(t);")

        # Build connection wiring
        connection_code = self._generate_connection_code(model_info)

        # Build output getter
        output_code = "        0.0"
        if model_info.sink_blocks:
            first_sink_id = model_info.sink_blocks[0]
            sink_block = next((b for b in model_info.blocks if b.id == first_sink_id), None)
            if sink_block:
                var_name = f"block_{self.sanitize_identifier(sink_block.id)}"
                output_code = f"        self.{var_name}.get_output(port)"

        # Build integrator propagation
        integrator_code = self._generate_integrator_propagation(model_info)

        # Build default implementation
        default_fields = []
        for block in model_info.blocks:
            struct_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            default_fields.append(f"            {var_name}: blocks::{struct_name}::new(),")

        return f'''//! Simulation library
//! Generated by LibreSim Coder.

pub mod blocks;
pub mod integration;

use integration::IntegrationMethod;

/// Model containing all simulation blocks.
#[derive(Clone)]
pub struct Model {{
    pub time: f64,
{chr(10).join(block_members)}
}}

impl Model {{
    /// Create a new model
    pub fn new() -> Self {{
        Self {{
            time: 0.0,
{chr(10).join(default_fields)}
        }}
    }}

    /// Initialize the model
    pub fn init(&mut self) {{
        self.time = 0.0;
{chr(10).join(init_calls)}
    }}

    /// Wire block connections (update inputs from outputs)
    pub fn wire_connections(&mut self) {{
{connection_code}
    }}

    /// Execute one simulation step
    pub fn step(&mut self, t: f64, _dt: f64, _kpass: usize) {{
        self.time = t;

        // Wire connections
        self.wire_connections();

        // Update all blocks in execution order
{chr(10).join(update_calls)}
    }}

    /// Get model output
    pub fn get_output(&self, port: usize) -> f64 {{
{output_code}
    }}

    /// Propagate integrators using specified method
    pub fn propagate_integrators(&mut self, dt: f64, kpass: usize, method: IntegrationMethod) {{
{integrator_code}
    }}
}}

impl Default for Model {{
    fn default() -> Self {{
        Self::new()
    }}
}}
'''

    def _generate_blocks(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.rs with all block struct definitions."""
        header = '''//! Block definitions
//! Generated by LibreSim Coder.

#![allow(dead_code)]
#![allow(clippy::needless_return)]

'''
        # Generate struct declarations for each block
        structs = []
        for block in model_info.blocks:
            struct_code = self.generate_block_code(block)
            structs.append(struct_code)

        return header + "\n".join(structs)

    def _generate_connection_code(self, model_info: CompiledModelInfo) -> str:
        """Generate connection wiring code."""
        lines = []
        for block in model_info.blocks:
            var_name = f"block_{self.sanitize_identifier(block.id)}"
            for conn in block.input_connections:
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next(
                    (b for b in model_info.blocks if b.id == source_id), None
                )
                if source_block:
                    source_var = f"block_{self.sanitize_identifier(source_block.id)}"
                    if target_port is not None and target_port > 0:
                        lines.append(
                            f"        self.{var_name}.input{target_port} = "
                            f"self.{source_var}.get_output({source_port});"
                        )
                    else:
                        lines.append(
                            f"        self.{var_name}.input = "
                            f"self.{source_var}.get_output({source_port});"
                        )

        return "\n".join(lines) if lines else "        // No connections"

    def _generate_integrator_propagation(self, model_info: CompiledModelInfo) -> str:
        """Generate integrator propagation code for RK methods."""
        lines = []
        for block_id in model_info.integrator_blocks:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block and block.type == "integrator":
                var_name = f"block_{self.sanitize_identifier(block.id)}"
                lines.append(f'''        // Integrator: {block.name}
        integration::propagate_integrator(
            &mut self.{var_name}.state,
            &mut self.{var_name}.xd0,
            &mut self.{var_name}.xd1,
            &mut self.{var_name}.xd2,
            &mut self.{var_name}.xd3,
            self.{var_name}.get_derivative(),
            dt, kpass, method
        );''')

        return "\n".join(lines) if lines else "        // No integrators to propagate"

    def _generate_passthrough_block(self, block: BlockInfo, struct_name: str) -> str:
        """Generate a passthrough block for unsupported types."""
        return f"""
/// {block.name} - Passthrough (type: {block.type})
#[derive(Clone, Default)]
pub struct {struct_name} {{
    pub input: f64,
    pub output: f64,
}}

impl {struct_name} {{
    pub fn new() -> Self {{
        Self {{
            input: 0.0,
            output: 0.0,
        }}
    }}

    pub fn init(&mut self) {{
        self.input = 0.0;
        self.output = 0.0;
    }}

    pub fn update(&mut self, _t: f64) {{
        self.output = self.input;
    }}

    pub fn get_output(&self, _port: usize) -> f64 {{
        self.output
    }}
}}
"""

    def _generate_cargo(self, config: Any) -> str:
        """Generate Cargo.toml."""
        project_name = config.project_name.replace('-', '_')
        return f'''[package]
name = "{project_name}"
version = "0.1.0"
edition = "2021"
description = "Simulation generated by LibreSim Coder"

[dependencies]

[[bin]]
name = "simulation"
path = "src/main.rs"

[lib]
name = "{project_name}"
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
'''

    def _generate_readme(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate README.md."""
        return f'''# {config.project_name}

Rust simulation generated by LibreSim Coder.

## Quick Start

```bash
# Build in release mode
cargo build --release

# Run the simulation
cargo run --release
```

## Model Information

- **Blocks**: {len(model_info.blocks)}
- **Integration Method**: {config.integration_method.value}
- **Step Size**: {config.step_size}
- **Duration**: {config.start_time} to {config.stop_time} seconds

## Files

- `src/lib.rs` - Model struct and simulation logic
- `src/blocks.rs` - Block struct definitions
- `src/integration.rs` - Numerical integration methods
- `src/main.rs` - Example runner (outputs to results.csv)

## Customization

To modify simulation parameters, edit the constants in `main.rs`:

```rust
let mut t = {config.start_time}_f64;      // Start time
let dt = {config.step_size}_f64;          // Step size
let t_end = {config.stop_time}_f64;       // End time
```

## Performance

The generated code uses Rust's zero-cost abstractions and is compiled
with full optimizations in release mode. For best performance, always
use `cargo run --release` or `cargo build --release`.

## Docker Build

To create a standalone executable using Docker:

```bash
# Build using the provided script
./build.sh

# Or manually:
docker build -t {config.project_name}-builder .
docker run --rm -v $(pwd)/output:/output {config.project_name}-builder
```

The executable will be created in the `output/` directory.
'''

    def _generate_dockerfile(self, config: Any) -> str:
        """Generate Dockerfile for compilation."""
        return f'''# Dockerfile for compiling {config.project_name}
# Generated by LibreSim Coder

FROM rust:1.75-bookworm

LABEL maintainer="LibreSim Coder"
LABEL description="Build environment for {config.project_name}"

# Set working directory
WORKDIR /build

# Copy project files
COPY . /build/

# Build the project in release mode
RUN cargo build --release

# Create output directory and copy executable
RUN mkdir -p /output && cp target/release/simulation /output/

# Default command copies the executable to mounted output
CMD ["cp", "/output/simulation", "/output/"]
'''

    def _generate_build_script(self, config: Any) -> str:
        """Generate build script."""
        return f'''#!/bin/bash
# Build script for {config.project_name}
# Generated by LibreSim Coder

set -e

PROJECT_NAME="{config.project_name}"
IMAGE_NAME="${{PROJECT_NAME}}-builder"

echo "=== Building $PROJECT_NAME (Rust) ==="

# Create output directory
mkdir -p output

# Build Docker image
echo "Building Docker image..."
docker build -t "$IMAGE_NAME" .

# Run container to compile
echo "Compiling..."
docker run --rm -v "$(pwd)/output:/output" "$IMAGE_NAME"

echo "=== Build Complete ==="
echo "Executable: output/simulation"
ls -la output/
'''
