import type { BlockDefinition } from '../types/block'

export const aerospaceBlocks: BlockDefinition[] = [
  // Quaternion Operations
  {
    type: 'quaternion_normalize',
    category: 'aerospace',
    name: 'Quaternion Normalize',
    description: 'Normalize a quaternion to unit length [q0, q1, q2, q3]',
    inputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    outputs: [{ name: 'q_norm', dataType: 'double', dimensions: [4] }],
    parameters: [],
    icon: 'q/|q|',
  },
  {
    type: 'quaternion_multiply',
    category: 'aerospace',
    name: 'Quaternion Multiply',
    description: 'Multiply two quaternions using Hamilton product',
    inputs: [
      { name: 'q1', dataType: 'double', dimensions: [4] },
      { name: 'q2', dataType: 'double', dimensions: [4] },
    ],
    outputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    parameters: [],
    icon: 'q1*q2',
  },
  {
    type: 'quaternion_conjugate',
    category: 'aerospace',
    name: 'Quaternion Conjugate',
    description: 'Compute the conjugate of a quaternion',
    inputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    outputs: [{ name: 'q_conj', dataType: 'double', dimensions: [4] }],
    parameters: [],
    icon: 'q*',
  },
  {
    type: 'quaternion_to_euler',
    category: 'aerospace',
    name: 'Quaternion to Euler',
    description: 'Convert quaternion to Euler angles (radians)',
    inputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    outputs: [{ name: 'euler', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'sequence',
        type: 'select',
        default: 'ZYX',
        label: 'Rotation Sequence',
        options: [
          { value: 'ZYX', label: 'ZYX (yaw-pitch-roll)' },
          { value: 'ZXY', label: 'ZXY' },
          { value: 'YZX', label: 'YZX' },
          { value: 'YXZ', label: 'YXZ' },
          { value: 'XYZ', label: 'XYZ' },
          { value: 'XZY', label: 'XZY' },
        ],
      },
    ],
    icon: 'q->E',
  },
  {
    type: 'euler_to_quaternion',
    category: 'aerospace',
    name: 'Euler to Quaternion',
    description: 'Convert Euler angles (radians) to quaternion',
    inputs: [{ name: 'euler', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    parameters: [
      {
        name: 'sequence',
        type: 'select',
        default: 'ZYX',
        label: 'Rotation Sequence',
        options: [
          { value: 'ZYX', label: 'ZYX (yaw-pitch-roll)' },
          { value: 'ZXY', label: 'ZXY' },
          { value: 'YZX', label: 'YZX' },
          { value: 'YXZ', label: 'YXZ' },
          { value: 'XYZ', label: 'XYZ' },
          { value: 'XZY', label: 'XZY' },
        ],
      },
    ],
    icon: 'E->q',
  },
  {
    type: 'quaternion_rotate_vector',
    category: 'aerospace',
    name: 'Quaternion Rotate Vector',
    description: 'Rotate a 3D vector by a quaternion',
    inputs: [
      { name: 'q', dataType: 'double', dimensions: [4] },
      { name: 'v', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'v_rot', dataType: 'double', dimensions: [3] }],
    parameters: [],
    icon: 'qvq*',
  },
  {
    type: 'dcm_to_quaternion',
    category: 'aerospace',
    name: 'DCM to Quaternion',
    description: 'Convert Direction Cosine Matrix (3x3) to quaternion',
    inputs: [{ name: 'dcm', dataType: 'double', dimensions: [9] }],
    outputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    parameters: [],
    icon: 'DCM->q',
  },
  {
    type: 'quaternion_to_dcm',
    category: 'aerospace',
    name: 'Quaternion to DCM',
    description: 'Convert quaternion to Direction Cosine Matrix (3x3)',
    inputs: [{ name: 'q', dataType: 'double', dimensions: [4] }],
    outputs: [{ name: 'dcm', dataType: 'double', dimensions: [9] }],
    parameters: [],
    icon: 'q->DCM',
  },
  // Atmosphere and Environment
  {
    type: 'isa_atmosphere',
    category: 'aerospace',
    name: 'ISA Atmosphere',
    description: 'International Standard Atmosphere model',
    inputs: [{ name: 'altitude', dataType: 'double', dimensions: [1] }],
    outputs: [
      { name: 'temperature', dataType: 'double', dimensions: [1] },
      { name: 'pressure', dataType: 'double', dimensions: [1] },
      { name: 'density', dataType: 'double', dimensions: [1] },
      { name: 'speed_of_sound', dataType: 'double', dimensions: [1] },
    ],
    parameters: [],
    icon: 'ISA',
  },
  {
    type: 'flat_earth_gravity',
    category: 'aerospace',
    name: 'Flat Earth Gravity',
    description: 'Constant gravity model for flat Earth assumption',
    inputs: [],
    outputs: [{ name: 'g', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'g',
        type: 'number',
        default: 9.80665,
        label: 'Gravitational Acceleration (m/s^2)',
      },
    ],
    icon: 'g',
  },
  {
    type: 'wgs84_gravity',
    category: 'aerospace',
    name: 'WGS84 Gravity',
    description: 'WGS84 gravity model varying with latitude and altitude',
    inputs: [
      { name: 'latitude', dataType: 'double', dimensions: [1] },
      { name: 'altitude', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'g', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'WGS84',
  },
  // Dynamics
  {
    type: 'six_dof_euler',
    category: 'aerospace',
    name: '6-DOF (Euler)',
    description: '6 degrees of freedom rigid body dynamics with Euler angles',
    inputs: [
      { name: 'forces', dataType: 'double', dimensions: [3] },
      { name: 'moments', dataType: 'double', dimensions: [3] },
    ],
    outputs: [
      { name: 'position', dataType: 'double', dimensions: [3] },
      { name: 'velocity', dataType: 'double', dimensions: [3] },
      { name: 'euler', dataType: 'double', dimensions: [3] },
      { name: 'omega', dataType: 'double', dimensions: [3] },
    ],
    parameters: [
      {
        name: 'mass',
        type: 'number',
        default: 1,
        label: 'Mass (kg)',
      },
      {
        name: 'inertia',
        type: 'array',
        default: [1, 0, 0, 0, 1, 0, 0, 0, 1],
        label: 'Inertia Matrix (3x3, row-major)',
        description: 'Moments and products of inertia [Ixx, Ixy, Ixz, Iyx, Iyy, Iyz, Izx, Izy, Izz]',
      },
      {
        name: 'initialPosition',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Position [x, y, z] (m)',
      },
      {
        name: 'initialVelocity',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Velocity [u, v, w] (m/s)',
      },
      {
        name: 'initialEuler',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Euler Angles [phi, theta, psi] (rad)',
      },
      {
        name: 'initialOmega',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Angular Rates [p, q, r] (rad/s)',
      },
    ],
    icon: '6DOF',
  },
]
