import type { BlockDefinition } from '../types/block'

export const continuousBlocks: BlockDefinition[] = [
  {
    type: 'integrator',
    category: 'continuous',
    name: 'Integrator',
    description: 'Integrate input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'externalIC',
        type: 'boolean',
        default: false,
        label: 'External Initial Condition',
        description: 'Use external input for initial condition (adds second input port)',
      },
      {
        name: 'initialCondition',
        type: 'number',
        default: 0,
        label: 'Initial Condition',
        description: 'Initial value of integrator state (ignored if External IC is enabled)',
      },
      {
        name: 'limitOutput',
        type: 'boolean',
        default: false,
        label: 'Limit Output',
      },
      {
        name: 'upperLimit',
        type: 'number',
        default: Infinity,
        label: 'Upper Limit',
      },
      {
        name: 'lowerLimit',
        type: 'number',
        default: -Infinity,
        label: 'Lower Limit',
      },
    ],
    icon: '∫',
  },
  {
    type: 'derivative',
    category: 'continuous',
    name: 'Derivative',
    description: 'Differentiate input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'coefficient',
        type: 'number',
        default: 1,
        label: 'Coefficient',
        description: 'Derivative gain (N in Ns/(s+N))',
      },
    ],
    icon: 'd/dt',
  },
  {
    type: 'transfer_function',
    category: 'continuous',
    name: 'Transfer Function',
    description: 'Continuous-time transfer function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Numerator coefficients [b0, b1, ...]',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, 1],
        label: 'Denominator',
        description: 'Denominator coefficients [a0, a1, ...]',
      },
    ],
    icon: 'H(s)',
  },
  {
    type: 'state_space',
    category: 'continuous',
    name: 'State-Space',
    description: 'State-space model (A, B, C, D)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'A',
        type: 'array',
        default: [[0]],
        label: 'A Matrix',
        description: 'State matrix',
      },
      {
        name: 'B',
        type: 'array',
        default: [[1]],
        label: 'B Matrix',
        description: 'Input matrix',
      },
      {
        name: 'C',
        type: 'array',
        default: [[1]],
        label: 'C Matrix',
        description: 'Output matrix',
      },
      {
        name: 'D',
        type: 'array',
        default: [[0]],
        label: 'D Matrix',
        description: 'Feedthrough matrix',
      },
      {
        name: 'initialCondition',
        type: 'array',
        default: [0],
        label: 'Initial State',
        description: 'Initial state vector',
      },
    ],
    icon: 'SS',
  },
  {
    type: 'zero_pole',
    category: 'continuous',
    name: 'Zero-Pole',
    description: 'Transfer function by zeros and poles',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'zeros',
        type: 'array',
        default: [],
        label: 'Zeros',
        description: 'Zero locations',
      },
      {
        name: 'poles',
        type: 'array',
        default: [-1],
        label: 'Poles',
        description: 'Pole locations',
      },
      {
        name: 'gain',
        type: 'number',
        default: 1,
        label: 'Gain',
        description: 'System gain',
      },
    ],
    icon: 'ZP',
  },
  {
    type: 'transport_delay',
    category: 'continuous',
    name: 'Transport Delay',
    description: 'Delay signal by fixed time',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'delayTime',
        type: 'number',
        default: 1.0,
        label: 'Time Delay (s)',
        description: 'Delay time in seconds',
        min: 0,
      },
      {
        name: 'initialOutput',
        type: 'number',
        default: 0,
        label: 'Initial Output',
        description: 'Output value during initial delay period',
      },
    ],
    icon: 'Td',
  },
  {
    type: 'second_order',
    category: 'continuous',
    name: 'Second Order',
    description: 'Second order system (mass-spring-damper)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'naturalFrequency',
        type: 'number',
        default: 1.0,
        label: 'Natural Frequency (rad/s)',
        description: 'Undamped natural frequency',
        min: 0.001,
      },
      {
        name: 'dampingRatio',
        type: 'number',
        default: 0.7,
        label: 'Damping Ratio',
        description: 'Damping ratio (0=undamped, 1=critical)',
        min: 0,
      },
      {
        name: 'gain',
        type: 'number',
        default: 1,
        label: 'DC Gain',
        description: 'Steady-state gain',
      },
    ],
    icon: '2nd',
  },
  {
    type: 'limited_integrator',
    category: 'continuous',
    name: 'Limited Integrator',
    description: 'Integrator with saturation limits',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'initialCondition',
        type: 'number',
        default: 0,
        label: 'Initial Condition',
      },
      {
        name: 'upperLimit',
        type: 'number',
        default: 1,
        label: 'Upper Saturation Limit',
      },
      {
        name: 'lowerLimit',
        type: 'number',
        default: -1,
        label: 'Lower Saturation Limit',
      },
    ],
    icon: '∫lim',
  },
]
