import type { BlockDefinition } from '../types/block'

export const controlDesignBlocks: BlockDefinition[] = [
  {
    type: 'lqr_controller',
    category: 'control_design',
    name: 'LQR Controller',
    description: 'Linear Quadratic Regulator: optimal state feedback controller (u = -K*x)',
    inputs: [{ name: 'x', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'u', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'K',
        type: 'array',
        default: [[1]],
        label: 'Gain Matrix K',
        description: 'State feedback gain matrix (computed from LQR design)',
      },
    ],
    icon: 'LQR',
  },
  {
    type: 'pole_placement',
    category: 'control_design',
    name: 'Pole Placement',
    description: 'State feedback controller with pole placement gain',
    inputs: [{ name: 'x', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'u', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'K',
        type: 'array',
        default: [[1]],
        label: 'Gain Matrix K',
        description: 'State feedback gain matrix (computed from pole placement)',
      },
    ],
    icon: 'Poles',
  },
  {
    type: 'lead_lag_compensator',
    category: 'control_design',
    name: 'Lead-Lag Compensator',
    description: 'Classical lead-lag compensator: K*(s+z)/(s+p)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'K',
        type: 'number',
        default: 1,
        label: 'Gain K',
        description: 'Compensator gain',
      },
      {
        name: 'zero',
        type: 'number',
        default: 1,
        label: 'Zero (z)',
        description: 'Zero location (positive value)',
      },
      {
        name: 'pole',
        type: 'number',
        default: 10,
        label: 'Pole (p)',
        description: 'Pole location (positive value)',
      },
    ],
    icon: 'Lead/Lag',
  },
  {
    type: 'pi_controller',
    category: 'control_design',
    name: 'PI Controller',
    description: 'Proportional-Integral controller',
    inputs: [{ name: 'error', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'u', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1,
        label: 'Proportional Gain (Kp)',
      },
      {
        name: 'Ki',
        type: 'number',
        default: 1,
        label: 'Integral Gain (Ki)',
      },
    ],
    icon: 'PI',
  },
  {
    type: 'pd_controller',
    category: 'control_design',
    name: 'PD Controller',
    description: 'Proportional-Derivative controller with derivative filter',
    inputs: [{ name: 'error', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'u', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1,
        label: 'Proportional Gain (Kp)',
      },
      {
        name: 'Kd',
        type: 'number',
        default: 0.1,
        label: 'Derivative Gain (Kd)',
      },
      {
        name: 'N',
        type: 'number',
        default: 100,
        label: 'Filter Coefficient (N)',
        description: 'Derivative filter coefficient (higher = less filtering)',
      },
    ],
    icon: 'PD',
  },
  {
    type: 'anti_windup_pid',
    category: 'control_design',
    name: 'Anti-Windup PID',
    description: 'PID controller with back-calculation anti-windup',
    inputs: [{ name: 'error', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'u', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1,
        label: 'Proportional Gain (Kp)',
      },
      {
        name: 'Ki',
        type: 'number',
        default: 1,
        label: 'Integral Gain (Ki)',
      },
      {
        name: 'Kd',
        type: 'number',
        default: 0.1,
        label: 'Derivative Gain (Kd)',
      },
      {
        name: 'N',
        type: 'number',
        default: 100,
        label: 'Filter Coefficient (N)',
      },
      {
        name: 'Kb',
        type: 'number',
        default: 1,
        label: 'Back-calculation Gain (Kb)',
        description: 'Anti-windup tracking gain (typically equals Ki)',
      },
      {
        name: 'upperLimit',
        type: 'number',
        default: 1,
        label: 'Upper Saturation Limit',
      },
      {
        name: 'lowerLimit',
        type: 'number',
        default: -1,
        label: 'Lower Saturation Limit',
      },
    ],
    icon: 'PID+AW',
  },
  {
    type: 'model_reference',
    category: 'control_design',
    name: 'Model Reference',
    description: 'Reference model for model reference adaptive control',
    inputs: [{ name: 'r', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'y', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'A',
        type: 'array',
        default: [[-1]],
        label: 'State Matrix (A)',
      },
      {
        name: 'B',
        type: 'array',
        default: [[1]],
        label: 'Input Matrix (B)',
      },
      {
        name: 'C',
        type: 'array',
        default: [[1]],
        label: 'Output Matrix (C)',
      },
      {
        name: 'D',
        type: 'array',
        default: [[0]],
        label: 'Feedthrough Matrix (D)',
      },
      {
        name: 'initialState',
        type: 'array',
        default: [0],
        label: 'Initial State',
      },
    ],
    icon: 'Ref',
  },
  {
    type: 'pid_controller',
    category: 'control_design',
    name: 'PID Controller',
    description: 'Continuous PID controller',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1,
        label: 'Proportional (Kp)',
        description: 'Proportional gain',
      },
      {
        name: 'Ki',
        type: 'number',
        default: 0,
        label: 'Integral (Ki)',
        description: 'Integral gain',
      },
      {
        name: 'Kd',
        type: 'number',
        default: 0,
        label: 'Derivative (Kd)',
        description: 'Derivative gain',
      },
      {
        name: 'N',
        type: 'number',
        default: 100,
        label: 'Filter Coefficient (N)',
        description: 'Derivative filter coefficient',
      },
      {
        name: 'initialConditionI',
        type: 'number',
        default: 0,
        label: 'Initial Integrator',
        description: 'Initial condition for integrator',
      },
    ],
    icon: 'PID',
  },
  {
    type: 'discrete_pid_controller',
    category: 'control_design',
    name: 'Discrete PID',
    description: 'Discrete PID controller',
    inputs: [{ name: 'error', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'control', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1,
        label: 'Proportional Gain',
      },
      {
        name: 'Ki',
        type: 'number',
        default: 0,
        label: 'Integral Gain',
      },
      {
        name: 'Kd',
        type: 'number',
        default: 0,
        label: 'Derivative Gain',
      },
      {
        name: 'N',
        type: 'number',
        default: 100,
        label: 'Filter Coefficient',
        description: 'Derivative filter coefficient',
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
      },
      {
        name: 'method',
        type: 'select',
        default: 'forward',
        label: 'Discretization Method',
        options: [
          { value: 'forward', label: 'Forward Euler' },
          { value: 'backward', label: 'Backward Euler' },
          { value: 'trapezoidal', label: 'Trapezoidal' },
        ],
      },
    ],
    icon: 'PID_d',
  },
]
