import type { BlockDefinition } from '../types/block'

export const continuousBlocks: BlockDefinition[] = [
  {
    type: 'integrator',
    category: 'continuous',
    name: 'Integrator',
    description: 'Integrate input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'initialCondition',
        type: 'number',
        default: 0,
        label: 'Initial Condition',
        description: 'Initial value of integrator state',
      },
      {
        name: 'limitOutput',
        type: 'boolean',
        default: false,
        label: 'Limit Output',
      },
      {
        name: 'upperLimit',
        type: 'number',
        default: Infinity,
        label: 'Upper Limit',
      },
      {
        name: 'lowerLimit',
        type: 'number',
        default: -Infinity,
        label: 'Lower Limit',
      },
    ],
    icon: '∫',
  },
  {
    type: 'derivative',
    category: 'continuous',
    name: 'Derivative',
    description: 'Differentiate input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'coefficient',
        type: 'number',
        default: 1,
        label: 'Coefficient',
        description: 'Derivative gain (N in Ns/(s+N))',
      },
    ],
    icon: 'd/dt',
  },
  {
    type: 'transfer_function',
    category: 'continuous',
    name: 'Transfer Function',
    description: 'Continuous-time transfer function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Numerator coefficients [b0, b1, ...]',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, 1],
        label: 'Denominator',
        description: 'Denominator coefficients [a0, a1, ...]',
      },
    ],
    icon: 'H(s)',
  },
  {
    type: 'state_space',
    category: 'continuous',
    name: 'State-Space',
    description: 'State-space model (A, B, C, D)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'A',
        type: 'array',
        default: [[0]],
        label: 'A Matrix',
        description: 'State matrix',
      },
      {
        name: 'B',
        type: 'array',
        default: [[1]],
        label: 'B Matrix',
        description: 'Input matrix',
      },
      {
        name: 'C',
        type: 'array',
        default: [[1]],
        label: 'C Matrix',
        description: 'Output matrix',
      },
      {
        name: 'D',
        type: 'array',
        default: [[0]],
        label: 'D Matrix',
        description: 'Feedthrough matrix',
      },
      {
        name: 'initialCondition',
        type: 'array',
        default: [0],
        label: 'Initial State',
        description: 'Initial state vector',
      },
    ],
    icon: 'SS',
  },
  {
    type: 'pid_controller',
    category: 'continuous',
    name: 'PID Controller',
    description: 'Continuous PID controller',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1,
        label: 'Proportional (Kp)',
        description: 'Proportional gain',
      },
      {
        name: 'Ki',
        type: 'number',
        default: 0,
        label: 'Integral (Ki)',
        description: 'Integral gain',
      },
      {
        name: 'Kd',
        type: 'number',
        default: 0,
        label: 'Derivative (Kd)',
        description: 'Derivative gain',
      },
      {
        name: 'N',
        type: 'number',
        default: 100,
        label: 'Filter Coefficient (N)',
        description: 'Derivative filter coefficient',
      },
      {
        name: 'initialConditionI',
        type: 'number',
        default: 0,
        label: 'Initial Integrator',
        description: 'Initial condition for integrator',
      },
    ],
    icon: 'PID',
  },
  {
    type: 'zero_pole',
    category: 'continuous',
    name: 'Zero-Pole',
    description: 'Transfer function by zeros and poles',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'zeros',
        type: 'array',
        default: [],
        label: 'Zeros',
        description: 'Zero locations',
      },
      {
        name: 'poles',
        type: 'array',
        default: [-1],
        label: 'Poles',
        description: 'Pole locations',
      },
      {
        name: 'gain',
        type: 'number',
        default: 1,
        label: 'Gain',
        description: 'System gain',
      },
    ],
    icon: 'ZP',
  },
]
