import type { BlockDefinition } from '../types/block'

export const controlAnalysisBlocks: BlockDefinition[] = [
  {
    type: 'bode_plot',
    category: 'control_analysis',
    name: 'Bode Plot',
    description: 'Frequency response (magnitude/phase) analysis',
    inputs: [],
    outputs: [{ name: 'dcGain', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Transfer function numerator coefficients',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, 1],
        label: 'Denominator',
        description: 'Transfer function denominator coefficients',
      },
      {
        name: 'minFrequency',
        type: 'number',
        default: 0.01,
        label: 'Min Frequency (Hz)',
        description: 'Minimum frequency for analysis',
        min: 0.0001,
      },
      {
        name: 'maxFrequency',
        type: 'number',
        default: 100,
        label: 'Max Frequency (Hz)',
        description: 'Maximum frequency for analysis',
        min: 0.01,
      },
      {
        name: 'numPoints',
        type: 'number',
        default: 200,
        label: 'Number of Points',
        description: 'Number of frequency points',
        min: 10,
        max: 1000,
      },
    ],
    icon: 'Bode',
  },
  {
    type: 'nyquist_plot',
    category: 'control_analysis',
    name: 'Nyquist Plot',
    description: 'Nyquist diagram for stability analysis',
    inputs: [],
    outputs: [{ name: 'encirclements', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Transfer function numerator coefficients',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, 1],
        label: 'Denominator',
        description: 'Transfer function denominator coefficients',
      },
      {
        name: 'minFrequency',
        type: 'number',
        default: 0.001,
        label: 'Min Frequency (Hz)',
        min: 0.0001,
      },
      {
        name: 'maxFrequency',
        type: 'number',
        default: 1000,
        label: 'Max Frequency (Hz)',
        min: 0.01,
      },
      {
        name: 'numPoints',
        type: 'number',
        default: 500,
        label: 'Number of Points',
        min: 50,
        max: 2000,
      },
    ],
    icon: 'Nyq',
  },
  {
    type: 'pole_zero_map',
    category: 'control_analysis',
    name: 'Pole-Zero Map',
    description: 'Display poles and zeros on s-plane',
    inputs: [],
    outputs: [{ name: 'isStable', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Transfer function numerator coefficients',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, 1],
        label: 'Denominator',
        description: 'Transfer function denominator coefficients',
      },
    ],
    icon: 'P/Z',
  },
  {
    type: 'step_info',
    category: 'control_analysis',
    name: 'Step Response Info',
    description: 'Compute step response characteristics',
    inputs: [],
    outputs: [{ name: 'settlingTime', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Transfer function numerator coefficients',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, 1],
        label: 'Denominator',
        description: 'Transfer function denominator coefficients',
      },
      {
        name: 'simulationTime',
        type: 'number',
        default: 10,
        label: 'Simulation Time (s)',
        description: 'Time to simulate step response',
        min: 0.1,
      },
      {
        name: 'numPoints',
        type: 'number',
        default: 1000,
        label: 'Number of Points',
        min: 100,
        max: 10000,
      },
      {
        name: 'settlingPercent',
        type: 'number',
        default: 2,
        label: 'Settling Threshold (%)',
        description: 'Percentage threshold for settling time',
        min: 0.1,
        max: 10,
      },
    ],
    icon: 'Step',
  },
]
