import type { BlockDefinition } from '../types/block'

export const discreteBlocks: BlockDefinition[] = [
  {
    type: 'unit_delay',
    category: 'discrete',
    name: 'Unit Delay',
    description: 'Delay signal by one sample period',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'initialCondition',
        type: 'number',
        default: 0,
        label: 'Initial Condition',
        description: 'Output at first sample',
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
        description: 'Discrete sample period',
      },
    ],
    icon: '1/z',
  },
  {
    type: 'zero_order_hold',
    category: 'discrete',
    name: 'Zero-Order Hold',
    description: 'Sample and hold input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
        description: 'Sample period',
      },
    ],
    icon: 'ZOH',
  },
  {
    type: 'discrete_integrator',
    category: 'discrete',
    name: 'Discrete Integrator',
    description: 'Discrete-time integrator',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'method',
        type: 'select',
        default: 'forward',
        label: 'Integration Method',
        options: [
          { value: 'forward', label: 'Forward Euler' },
          { value: 'backward', label: 'Backward Euler' },
          { value: 'trapezoidal', label: 'Trapezoidal' },
        ],
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
      },
      {
        name: 'initialCondition',
        type: 'number',
        default: 0,
        label: 'Initial Condition',
      },
    ],
    icon: 'K*Ts/z',
  },
  {
    type: 'discrete_derivative',
    category: 'discrete',
    name: 'Discrete Derivative',
    description: 'Discrete-time derivative',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
      },
      {
        name: 'initialCondition',
        type: 'number',
        default: 0,
        label: 'Initial Condition',
        description: 'Previous input value at start',
      },
    ],
    icon: 'du/dt',
  },
  {
    type: 'discrete_transfer_function',
    category: 'discrete',
    name: 'Discrete Transfer Fcn',
    description: 'Discrete-time transfer function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [1],
        label: 'Numerator',
        description: 'Numerator coefficients',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1, -0.5],
        label: 'Denominator',
        description: 'Denominator coefficients',
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
      },
    ],
    icon: 'H(z)',
  },
  {
    type: 'discrete_filter',
    category: 'discrete',
    name: 'Discrete Filter',
    description: 'General IIR/FIR filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [0.5, 0.5],
        label: 'Numerator (b)',
        description: 'FIR coefficients',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1],
        label: 'Denominator (a)',
        description: 'IIR coefficients',
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time',
      },
    ],
    icon: 'IIR',
  },
]
