import type { BlockDefinition } from '../types/block'

export const dspBlocks: BlockDefinition[] = [
  // Transform Operations
  {
    type: 'fft',
    category: 'dsp',
    name: 'FFT',
    description: 'Compute Fast Fourier Transform of input signal',
    inputs: [{ name: 'signal', dataType: 'double', dimensions: [-1] }],
    outputs: [{ name: 'spectrum', dataType: 'double', dimensions: [-1] }],
    parameters: [
      {
        name: 'nPoints',
        type: 'number',
        default: 64,
        label: 'FFT Length',
        description: 'Number of FFT points (power of 2 recommended)',
        min: 2,
        step: 1,
      },
    ],
    icon: 'FFT',
  },
  {
    type: 'ifft',
    category: 'dsp',
    name: 'IFFT',
    description: 'Compute Inverse Fast Fourier Transform',
    inputs: [{ name: 'spectrum', dataType: 'double', dimensions: [-1] }],
    outputs: [{ name: 'signal', dataType: 'double', dimensions: [-1] }],
    parameters: [
      {
        name: 'nPoints',
        type: 'number',
        default: 64,
        label: 'IFFT Length',
        min: 2,
        step: 1,
      },
    ],
    icon: 'IFFT',
  },
  // Digital Filters
  {
    type: 'fir_filter',
    category: 'dsp',
    name: 'FIR Filter',
    description: 'Finite Impulse Response digital filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'coefficients',
        type: 'array',
        default: [0.25, 0.5, 0.25],
        label: 'Filter Coefficients (b)',
        description: 'Numerator polynomial coefficients',
      },
    ],
    icon: 'FIR',
  },
  {
    type: 'iir_filter',
    category: 'dsp',
    name: 'IIR Filter',
    description: 'Infinite Impulse Response digital filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numerator',
        type: 'array',
        default: [0.0675, 0.1349, 0.0675],
        label: 'Numerator Coefficients (b)',
      },
      {
        name: 'denominator',
        type: 'array',
        default: [1.0, -1.143, 0.4128],
        label: 'Denominator Coefficients (a)',
      },
    ],
    icon: 'IIR',
  },
  {
    type: 'convolution',
    category: 'dsp',
    name: 'Convolution',
    description: 'Convolve input signal with kernel',
    inputs: [{ name: 'signal', dataType: 'double', dimensions: [-1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [-1] }],
    parameters: [
      {
        name: 'kernel',
        type: 'array',
        default: [0.25, 0.5, 0.25],
        label: 'Convolution Kernel',
      },
    ],
    icon: 'x*h',
  },
  // Sample Rate Conversion
  {
    type: 'downsampler',
    category: 'dsp',
    name: 'Downsampler',
    description: 'Reduce sample rate by integer factor',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'factor',
        type: 'number',
        default: 2,
        label: 'Downsample Factor',
        min: 1,
        step: 1,
      },
    ],
    icon: '↓N',
  },
  {
    type: 'upsampler',
    category: 'dsp',
    name: 'Upsampler',
    description: 'Increase sample rate by integer factor (zero insertion)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'factor',
        type: 'number',
        default: 2,
        label: 'Upsample Factor',
        min: 1,
        step: 1,
      },
    ],
    icon: '↑N',
  },
  {
    type: 'interpolator',
    category: 'dsp',
    name: 'Interpolator',
    description: 'Upsample with interpolation filtering',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'factor',
        type: 'number',
        default: 2,
        label: 'Interpolation Factor',
        min: 1,
        step: 1,
      },
      {
        name: 'method',
        type: 'select',
        default: 'linear',
        label: 'Interpolation Method',
        options: [
          { value: 'linear', label: 'Linear' },
          { value: 'hold', label: 'Zero-Order Hold' },
        ],
      },
    ],
    icon: '↑Int',
  },
  // Window Functions
  {
    type: 'window_function',
    category: 'dsp',
    name: 'Window Function',
    description: 'Apply window function to input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [-1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [-1] }],
    parameters: [
      {
        name: 'windowType',
        type: 'select',
        default: 'hamming',
        label: 'Window Type',
        options: [
          { value: 'rectangular', label: 'Rectangular' },
          { value: 'hamming', label: 'Hamming' },
          { value: 'hanning', label: 'Hanning' },
          { value: 'blackman', label: 'Blackman' },
          { value: 'kaiser', label: 'Kaiser' },
        ],
      },
      {
        name: 'beta',
        type: 'number',
        default: 5.0,
        label: 'Kaiser Beta',
        description: 'Shape parameter for Kaiser window',
        min: 0,
      },
    ],
    icon: 'Win',
  },
  // Statistics
  {
    type: 'mean',
    category: 'dsp',
    name: 'Mean',
    description: 'Compute running mean of input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'mean', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'windowSize',
        type: 'number',
        default: 10,
        label: 'Window Size',
        min: 1,
        step: 1,
      },
    ],
    icon: 'μ',
  },
  {
    type: 'variance',
    category: 'dsp',
    name: 'Variance',
    description: 'Compute running variance of input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'variance', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'windowSize',
        type: 'number',
        default: 10,
        label: 'Window Size',
        min: 1,
        step: 1,
      },
    ],
    icon: 'σ²',
  },
  {
    type: 'rms',
    category: 'dsp',
    name: 'RMS',
    description: 'Compute running RMS (Root Mean Square) of input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'rms', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'windowSize',
        type: 'number',
        default: 10,
        label: 'Window Size',
        min: 1,
        step: 1,
      },
    ],
    icon: 'RMS',
  },
  // Signal Detection
  {
    type: 'peak_detector',
    category: 'dsp',
    name: 'Peak Detector',
    description: 'Detect peaks in input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [
      { name: 'isPeak', dataType: 'double', dimensions: [1] },
      { name: 'peakValue', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 'threshold',
        type: 'number',
        default: 0.0,
        label: 'Threshold',
        description: 'Minimum value to consider as peak',
      },
      {
        name: 'minDistance',
        type: 'number',
        default: 1,
        label: 'Min Distance',
        description: 'Minimum samples between peaks',
        min: 1,
        step: 1,
      },
    ],
    icon: '∧',
  },
  {
    type: 'zero_crossing_detector',
    category: 'dsp',
    name: 'Zero Crossing Detector',
    description: 'Detect zero crossings in input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [
      { name: 'crossing', dataType: 'double', dimensions: [1] },
      { name: 'direction', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 'direction',
        type: 'select',
        default: 'both',
        label: 'Detection Direction',
        options: [
          { value: 'both', label: 'Both' },
          { value: 'rising', label: 'Rising' },
          { value: 'falling', label: 'Falling' },
        ],
      },
    ],
    icon: '0×',
  },
]
