import type { BlockDefinition } from '../types/block'

export const mathBlocks: BlockDefinition[] = [
  {
    type: 'sum',
    category: 'math',
    name: 'Sum',
    description: 'Add or subtract inputs',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'signs',
        type: 'string',
        default: '++',
        label: 'Sign List',
        description: 'Input signs (e.g., "++", "+-", "+++")',
      },
    ],
    icon: 'Σ',
  },
  {
    type: 'gain',
    category: 'math',
    name: 'Gain',
    description: 'Multiply input by constant',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'gain',
        type: 'number',
        default: 1,
        label: 'Gain',
        description: 'Multiplication factor',
      },
    ],
    icon: 'K',
  },
  {
    type: 'product',
    category: 'math',
    name: 'Product',
    description: 'Multiply or divide inputs',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'operations',
        type: 'string',
        default: '**',
        label: 'Operations',
        description: 'Multiply (*) or divide (/) for each input',
      },
    ],
    icon: '×',
  },
  {
    type: 'abs',
    category: 'math',
    name: 'Abs',
    description: 'Absolute value',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '|u|',
  },
  {
    type: 'sign',
    category: 'math',
    name: 'Sign',
    description: 'Sign of input (-1, 0, or 1)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '±',
  },
  {
    type: 'math_function',
    category: 'math',
    name: 'Math Function',
    description: 'Mathematical function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'function',
        type: 'select',
        default: 'exp',
        label: 'Function',
        options: [
          { value: 'exp', label: 'exp' },
          { value: 'log', label: 'log (natural)' },
          { value: 'log10', label: 'log10' },
          { value: 'sqrt', label: 'sqrt' },
          { value: 'square', label: 'square (u^2)' },
          { value: 'pow', label: 'power (u^n)' },
          { value: 'reciprocal', label: 'reciprocal (1/u)' },
        ],
      },
      {
        name: 'exponent',
        type: 'number',
        default: 2,
        label: 'Exponent',
        description: 'For power function',
      },
    ],
    icon: 'f(u)',
  },
  {
    type: 'trigonometry',
    category: 'math',
    name: 'Trigonometric',
    description: 'Trigonometric function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'function',
        type: 'select',
        default: 'sin',
        label: 'Function',
        options: [
          { value: 'sin', label: 'sin' },
          { value: 'cos', label: 'cos' },
          { value: 'tan', label: 'tan' },
          { value: 'asin', label: 'asin' },
          { value: 'acos', label: 'acos' },
          { value: 'atan', label: 'atan' },
          { value: 'sinh', label: 'sinh' },
          { value: 'cosh', label: 'cosh' },
          { value: 'tanh', label: 'tanh' },
        ],
      },
    ],
    icon: 'sin',
  },
  {
    type: 'saturation',
    category: 'math',
    name: 'Saturation',
    description: 'Limit signal to range',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'upperLimit',
        type: 'number',
        default: 1,
        label: 'Upper Limit',
      },
      {
        name: 'lowerLimit',
        type: 'number',
        default: -1,
        label: 'Lower Limit',
      },
    ],
    icon: '⊏⊐',
  },
  {
    type: 'dead_zone',
    category: 'math',
    name: 'Dead Zone',
    description: 'Zero output within zone',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'start',
        type: 'number',
        default: -0.5,
        label: 'Start of Dead Zone',
      },
      {
        name: 'end',
        type: 'number',
        default: 0.5,
        label: 'End of Dead Zone',
      },
    ],
    icon: '⊔',
  },
  {
    type: 'dot_product',
    category: 'math',
    name: 'Dot Product',
    description: 'Compute dot product of two vectors',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '•',
  },
  {
    type: 'sqrt',
    category: 'math',
    name: 'Sqrt',
    description: 'Square root of input',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '√',
  },
  {
    type: 'unary_minus',
    category: 'math',
    name: 'Unary Minus',
    description: 'Negate input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '-u',
  },
  {
    type: 'minmax',
    category: 'math',
    name: 'MinMax',
    description: 'Output min or max of inputs',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'function',
        type: 'select',
        default: 'min',
        label: 'Function',
        options: [
          { value: 'min', label: 'Minimum' },
          { value: 'max', label: 'Maximum' },
        ],
      },
    ],
    icon: '↕',
  },
  {
    type: 'bias',
    category: 'math',
    name: 'Bias',
    description: 'Add bias to input',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'bias',
        type: 'number',
        default: 0,
        label: 'Bias',
        description: 'Value to add to input',
      },
    ],
    icon: '+b',
  },
  {
    type: 'divide',
    category: 'math',
    name: 'Divide',
    description: 'Divide first input by second',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '÷',
  },
  {
    type: 'mod',
    category: 'math',
    name: 'Mod',
    description: 'Modulo (remainder) operation',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '%',
  },
  {
    type: 'atan2',
    category: 'math',
    name: 'Atan2',
    description: 'Four-quadrant arctangent',
    inputs: [
      { name: 'y', dataType: 'double', dimensions: [1] },
      { name: 'x', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'atan2',
  },
  {
    type: 'rounding',
    category: 'math',
    name: 'Rounding',
    description: 'Round input value',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'function',
        type: 'select',
        default: 'round',
        label: 'Rounding Function',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'floor', label: 'Floor' },
          { value: 'ceil', label: 'Ceil' },
          { value: 'fix', label: 'Fix (toward zero)' },
        ],
      },
    ],
    icon: '⌊⌉',
  },
  {
    type: 'cross_product',
    category: 'math',
    name: 'Cross Product',
    description: 'Compute cross product of two 3D vectors',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [3] },
      { name: 'in2', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [3] }],
    parameters: [],
    icon: '×',
  },
  {
    type: 'hypot',
    category: 'math',
    name: 'Hypot',
    description: 'Euclidean distance (sqrt(x²+y²))',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '√Σ²',
  },
  {
    type: 'slider_gain',
    category: 'math',
    name: 'Slider Gain',
    description: 'Gain with adjustable range',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'gain',
        type: 'number',
        default: 1,
        label: 'Gain',
      },
      {
        name: 'min',
        type: 'number',
        default: 0,
        label: 'Minimum',
      },
      {
        name: 'max',
        type: 'number',
        default: 10,
        label: 'Maximum',
      },
    ],
    icon: '⊟K',
  },
  {
    type: 'weighted_sum',
    category: 'math',
    name: 'Weighted Sum',
    description: 'Sum inputs with weights',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'weights',
        type: 'array',
        default: [1, 1],
        label: 'Weights',
        description: 'Weights for each input',
      },
    ],
    icon: 'Σw',
  },
  {
    type: 'polynomial',
    category: 'math',
    name: 'Polynomial',
    description: 'Evaluate polynomial expression',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'coefficients',
        type: 'array',
        default: [1, 0, 0],
        label: 'Coefficients',
        description: 'Polynomial coefficients [a_n, ..., a_1, a_0]',
      },
    ],
    icon: 'p(u)',
  },
  {
    type: 'magnitude_angle',
    category: 'math',
    name: 'Magnitude-Angle to Complex',
    description: 'Convert magnitude and angle to complex number',
    inputs: [
      { name: 'mag', dataType: 'double', dimensions: [1] },
      { name: 'angle', dataType: 'double', dimensions: [1] },
    ],
    outputs: [
      { name: 'real', dataType: 'double', dimensions: [1] },
      { name: 'imag', dataType: 'double', dimensions: [1] },
    ],
    parameters: [],
    icon: 'r∠θ',
  },
  {
    type: 'complex_to_magnitude_angle',
    category: 'math',
    name: 'Complex to Magnitude-Angle',
    description: 'Convert complex number to magnitude and angle',
    inputs: [
      { name: 'real', dataType: 'double', dimensions: [1] },
      { name: 'imag', dataType: 'double', dimensions: [1] },
    ],
    outputs: [
      { name: 'mag', dataType: 'double', dimensions: [1] },
      { name: 'angle', dataType: 'double', dimensions: [1] },
    ],
    parameters: [],
    icon: '→r∠θ',
  },
  {
    type: 'sqrt',
    category: 'math',
    name: 'Sqrt',
    description: 'Square root of input',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '√',
  },
  {
    type: 'reciprocal',
    category: 'math',
    name: 'Reciprocal',
    description: 'Compute 1/u',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '1/u',
  },
  {
    type: 'square',
    category: 'math',
    name: 'Square',
    description: 'Compute u²',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'u²',
  },
  {
    type: 'power',
    category: 'math',
    name: 'Power',
    description: 'Raise first input to power of second',
    inputs: [
      { name: 'base', dataType: 'double', dimensions: [1] },
      { name: 'exponent', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'u^v',
  },
  {
    type: 'exp',
    category: 'math',
    name: 'Exp',
    description: 'Exponential function (e^u)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'eᵘ',
  },
  {
    type: 'log',
    category: 'math',
    name: 'Log',
    description: 'Natural logarithm',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'ln',
  },
  {
    type: 'log10',
    category: 'math',
    name: 'Log10',
    description: 'Base-10 logarithm',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'log₁₀',
  },
]
