import type { BlockDefinition } from '../types/block'

export const mathBlocks: BlockDefinition[] = [
  {
    type: 'sum',
    category: 'math',
    name: 'Sum',
    description: 'Add or subtract inputs',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'signs',
        type: 'string',
        default: '++',
        label: 'Sign List',
        description: 'Input signs (e.g., "++", "+-", "+++")',
      },
    ],
    icon: 'Σ',
  },
  {
    type: 'gain',
    category: 'math',
    name: 'Gain',
    description: 'Multiply input by constant',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'gain',
        type: 'number',
        default: 1,
        label: 'Gain',
        description: 'Multiplication factor',
      },
    ],
    icon: 'K',
  },
  {
    type: 'product',
    category: 'math',
    name: 'Product',
    description: 'Multiply or divide inputs',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'operations',
        type: 'string',
        default: '**',
        label: 'Operations',
        description: 'Multiply (*) or divide (/) for each input',
      },
    ],
    icon: '×',
  },
  {
    type: 'abs',
    category: 'math',
    name: 'Abs',
    description: 'Absolute value',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '|u|',
  },
  {
    type: 'sign',
    category: 'math',
    name: 'Sign',
    description: 'Sign of input (-1, 0, or 1)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '±',
  },
  {
    type: 'math_function',
    category: 'math',
    name: 'Math Function',
    description: 'Mathematical function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'function',
        type: 'select',
        default: 'exp',
        label: 'Function',
        options: [
          { value: 'exp', label: 'exp' },
          { value: 'log', label: 'log (natural)' },
          { value: 'log10', label: 'log10' },
          { value: 'sqrt', label: 'sqrt' },
          { value: 'square', label: 'square (u^2)' },
          { value: 'pow', label: 'power (u^n)' },
          { value: 'reciprocal', label: 'reciprocal (1/u)' },
        ],
      },
      {
        name: 'exponent',
        type: 'number',
        default: 2,
        label: 'Exponent',
        description: 'For power function',
      },
    ],
    icon: 'f(u)',
  },
  {
    type: 'trigonometry',
    category: 'math',
    name: 'Trigonometric',
    description: 'Trigonometric function',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'function',
        type: 'select',
        default: 'sin',
        label: 'Function',
        options: [
          { value: 'sin', label: 'sin' },
          { value: 'cos', label: 'cos' },
          { value: 'tan', label: 'tan' },
          { value: 'asin', label: 'asin' },
          { value: 'acos', label: 'acos' },
          { value: 'atan', label: 'atan' },
          { value: 'sinh', label: 'sinh' },
          { value: 'cosh', label: 'cosh' },
          { value: 'tanh', label: 'tanh' },
        ],
      },
    ],
    icon: 'sin',
  },
  {
    type: 'saturation',
    category: 'math',
    name: 'Saturation',
    description: 'Limit signal to range',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'upperLimit',
        type: 'number',
        default: 1,
        label: 'Upper Limit',
      },
      {
        name: 'lowerLimit',
        type: 'number',
        default: -1,
        label: 'Lower Limit',
      },
    ],
    icon: '⊏⊐',
  },
  {
    type: 'dead_zone',
    category: 'math',
    name: 'Dead Zone',
    description: 'Zero output within zone',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'start',
        type: 'number',
        default: -0.5,
        label: 'Start of Dead Zone',
      },
      {
        name: 'end',
        type: 'number',
        default: 0.5,
        label: 'End of Dead Zone',
      },
    ],
    icon: '⊔',
  },
]
