import type { BlockDefinition } from '../types/block'

export const matrixOpsBlocks: BlockDefinition[] = [
  {
    type: 'matrix_multiply',
    category: 'matrix_ops',
    name: 'Matrix Multiply',
    description: 'Multiply two matrices or vectors',
    inputs: [
      { name: 'A', dataType: 'double', dimensions: [1] },
      { name: 'B', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'A*B',
  },
  {
    type: 'matrix_transpose',
    category: 'matrix_ops',
    name: 'Matrix Transpose',
    description: 'Transpose a matrix or vector',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: "A'",
  },
  {
    type: 'matrix_inverse',
    category: 'matrix_ops',
    name: 'Matrix Inverse',
    description: 'Compute the inverse of a matrix',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'inv(A)',
  },
  {
    type: 'selector',
    category: 'matrix_ops',
    name: 'Selector',
    description: 'Select elements from a vector by index',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'indices',
        type: 'array',
        default: [0],
        label: 'Indices',
        description: 'Indices of elements to select (0-based)',
      },
    ],
    icon: 'Select',
  },
  {
    type: 'assignment',
    category: 'matrix_ops',
    name: 'Assignment',
    description: 'Assign values to specific indices of a vector',
    inputs: [
      { name: 'base', dataType: 'double', dimensions: [1] },
      { name: 'values', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'indices',
        type: 'array',
        default: [0],
        label: 'Indices',
        description: 'Indices where values should be assigned (0-based)',
      },
    ],
    icon: 'Assign',
  },
  {
    type: 'concatenate',
    category: 'matrix_ops',
    name: 'Concatenate',
    description: 'Concatenate multiple vectors',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numInputs',
        type: 'number',
        default: 2,
        label: 'Number of Inputs',
        min: 2,
        max: 10,
      },
      {
        name: 'mode',
        type: 'select',
        default: 'vertical',
        label: 'Concatenation Mode',
        options: [
          { value: 'vertical', label: 'Vertical (column)' },
          { value: 'horizontal', label: 'Horizontal (row)' },
        ],
      },
    ],
    icon: '[A;B]',
  },
  {
    type: 'matrix_sum',
    category: 'matrix_ops',
    name: 'Matrix Sum',
    description: 'Sum all elements of a vector or matrix',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'sum()',
  },
  {
    type: 'vector_norm',
    category: 'matrix_ops',
    name: 'Vector Norm',
    description: 'Compute the norm of a vector',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'normType',
        type: 'select',
        default: '2',
        label: 'Norm Type',
        options: [
          { value: '1', label: '1-norm (sum of absolute values)' },
          { value: '2', label: '2-norm (Euclidean)' },
          { value: 'inf', label: 'Infinity norm (maximum)' },
        ],
      },
    ],
    icon: '||x||',
  },
  {
    type: 'matrix_identity',
    category: 'matrix_ops',
    name: 'Matrix Identity',
    description: 'Create an n x n identity matrix',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'size',
        type: 'number',
        default: 3,
        label: 'Size (n x n)',
        description: 'Dimension of the identity matrix',
        min: 1,
      },
    ],
    icon: 'I(n)',
  },
  {
    type: 'matrix_zeros',
    category: 'matrix_ops',
    name: 'Matrix Zeros',
    description: 'Create a matrix of zeros',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'rows',
        type: 'number',
        default: 2,
        label: 'Rows',
        min: 1,
      },
      {
        name: 'cols',
        type: 'number',
        default: 2,
        label: 'Columns',
        min: 1,
      },
    ],
    icon: 'zeros',
  },
  {
    type: 'matrix_diagonal',
    category: 'matrix_ops',
    name: 'Matrix Diagonal',
    description: 'Build a diagonal matrix from a vector of values',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'values',
        type: 'array',
        default: [1, 1],
        label: 'Diagonal Values',
        description: 'Diagonal elements',
      },
    ],
    icon: 'diag',
  },
  {
    type: 'matrix_reshape',
    category: 'matrix_ops',
    name: 'Matrix Reshape',
    description: 'Reshape a flat vector or matrix to a new 2-D shape',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'rows',
        type: 'number',
        default: 2,
        label: 'Rows',
        min: 1,
      },
      {
        name: 'cols',
        type: 'number',
        default: 2,
        label: 'Columns',
        min: 1,
      },
    ],
    icon: 'reshape',
  },
  {
    type: 'linear_solve',
    category: 'matrix_ops',
    name: 'Linear Solve',
    description: 'Solve A x = b by LU factorization; vector or multiple right-hand sides',
    inputs: [
      { name: 'A', dataType: 'double', dimensions: [1] },
      { name: 'b', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'x', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'method',
        type: 'select',
        default: 'lu',
        label: 'Method',
        options: [{ value: 'lu', label: 'LU (partial pivoting)' }],
      },
      {
        name: 'pivoting',
        type: 'select',
        default: 'partial',
        label: 'Pivoting',
        options: [{ value: 'partial', label: 'Partial' }],
      },
      {
        name: 'singularityTolerance',
        type: 'number',
        default: 1e-12,
        label: 'Singularity Tolerance',
      },
      {
        name: 'conditionLimit',
        type: 'number',
        default: 4.5e15,
        label: 'Condition Limit',
      },
      {
        name: 'failurePolicy',
        type: 'select',
        default: 'status',
        label: 'Failure Policy',
        options: [
          { value: 'status', label: 'Report status (no throw)' },
          { value: 'raise', label: 'Raise on failure' },
        ],
      },
    ],
    icon: 'solve',
  },
]
