import type { BlockDefinition } from '../types/block'

export const matrixOpsBlocks: BlockDefinition[] = [
  {
    type: 'matrix_multiply',
    category: 'matrix_ops',
    name: 'Matrix Multiply',
    description: 'Multiply two matrices or vectors',
    inputs: [
      { name: 'A', dataType: 'double', dimensions: [1] },
      { name: 'B', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'A*B',
  },
  {
    type: 'matrix_transpose',
    category: 'matrix_ops',
    name: 'Matrix Transpose',
    description: 'Transpose a matrix or vector',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: "A'",
  },
  {
    type: 'matrix_inverse',
    category: 'matrix_ops',
    name: 'Matrix Inverse',
    description: 'Compute the inverse of a matrix',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'inv(A)',
  },
  {
    type: 'selector',
    category: 'matrix_ops',
    name: 'Selector',
    description: 'Select elements from a vector by index',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'indices',
        type: 'array',
        default: [0],
        label: 'Indices',
        description: 'Indices of elements to select (0-based)',
      },
    ],
    icon: 'Select',
  },
  {
    type: 'assignment',
    category: 'matrix_ops',
    name: 'Assignment',
    description: 'Assign values to specific indices of a vector',
    inputs: [
      { name: 'base', dataType: 'double', dimensions: [1] },
      { name: 'values', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'indices',
        type: 'array',
        default: [0],
        label: 'Indices',
        description: 'Indices where values should be assigned (0-based)',
      },
    ],
    icon: 'Assign',
  },
  {
    type: 'concatenate',
    category: 'matrix_ops',
    name: 'Concatenate',
    description: 'Concatenate multiple vectors',
    inputs: [
      { name: 'in1', dataType: 'double', dimensions: [1] },
      { name: 'in2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'numInputs',
        type: 'number',
        default: 2,
        label: 'Number of Inputs',
        min: 2,
        max: 10,
      },
      {
        name: 'mode',
        type: 'select',
        default: 'vertical',
        label: 'Concatenation Mode',
        options: [
          { value: 'vertical', label: 'Vertical (column)' },
          { value: 'horizontal', label: 'Horizontal (row)' },
        ],
      },
    ],
    icon: '[A;B]',
  },
  {
    type: 'matrix_sum',
    category: 'matrix_ops',
    name: 'Matrix Sum',
    description: 'Sum all elements of a vector or matrix',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'sum()',
  },
  {
    type: 'vector_norm',
    category: 'matrix_ops',
    name: 'Vector Norm',
    description: 'Compute the norm of a vector',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'normType',
        type: 'select',
        default: '2',
        label: 'Norm Type',
        options: [
          { value: '1', label: '1-norm (sum of absolute values)' },
          { value: '2', label: '2-norm (Euclidean)' },
          { value: 'inf', label: 'Infinity norm (maximum)' },
        ],
      },
    ],
    icon: '||x||',
  },
]
