import type { BlockDefinition } from '../types/block'

export const navigationBlocks: BlockDefinition[] = [
  // Coordinate Transformations
  {
    type: 'coordinate_transformation',
    category: 'navigation',
    name: 'Coordinate Transformation',
    description: 'Convert between coordinate representations (LLA, ECEF, NED, Euler, DCM, Quaternion)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [-1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [-1] }],
    parameters: [
      {
        name: 'inputFrame',
        type: 'select',
        default: 'lla',
        label: 'Input Frame',
        options: [
          { value: 'lla', label: 'LLA (Geodetic)' },
          { value: 'ecef', label: 'ECEF' },
          { value: 'ned', label: 'NED' },
          { value: 'euler', label: 'Euler Angles' },
          { value: 'dcm', label: 'DCM (3x3)' },
          { value: 'quaternion', label: 'Quaternion' },
          { value: 'axis_angle', label: 'Axis-Angle' },
        ],
      },
      {
        name: 'outputFrame',
        type: 'select',
        default: 'ecef',
        label: 'Output Frame',
        options: [
          { value: 'lla', label: 'LLA (Geodetic)' },
          { value: 'ecef', label: 'ECEF' },
          { value: 'ned', label: 'NED' },
          { value: 'euler', label: 'Euler Angles' },
          { value: 'dcm', label: 'DCM (3x3)' },
          { value: 'quaternion', label: 'Quaternion' },
          { value: 'axis_angle', label: 'Axis-Angle' },
        ],
      },
      {
        name: 'referenceLat',
        type: 'number',
        default: 0.0,
        label: 'Reference Latitude (deg)',
        description: 'Reference point for NED conversions',
      },
      {
        name: 'referenceLon',
        type: 'number',
        default: 0.0,
        label: 'Reference Longitude (deg)',
      },
      {
        name: 'referenceAlt',
        type: 'number',
        default: 0.0,
        label: 'Reference Altitude (m)',
      },
    ],
    icon: 'CT',
  },
  {
    type: 'lla_to_ecef',
    category: 'navigation',
    name: 'LLA to ECEF',
    description: 'Convert geodetic coordinates (lat, lon, alt) to Earth-Centered Earth-Fixed',
    inputs: [{ name: 'lla', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'ecef', dataType: 'double', dimensions: [3] }],
    parameters: [],
    icon: 'LLA→ECEF',
  },
  {
    type: 'ecef_to_lla',
    category: 'navigation',
    name: 'ECEF to LLA',
    description: 'Convert ECEF coordinates to geodetic (lat, lon, alt)',
    inputs: [{ name: 'ecef', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'lla', dataType: 'double', dimensions: [3] }],
    parameters: [],
    icon: 'ECEF→LLA',
  },
  {
    type: 'ecef_to_ned',
    category: 'navigation',
    name: 'ECEF to NED',
    description: 'Convert ECEF to North-East-Down coordinates relative to reference point',
    inputs: [{ name: 'ecef', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'ned', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'referenceLat',
        type: 'number',
        default: 0.0,
        label: 'Reference Latitude (deg)',
      },
      {
        name: 'referenceLon',
        type: 'number',
        default: 0.0,
        label: 'Reference Longitude (deg)',
      },
      {
        name: 'referenceAlt',
        type: 'number',
        default: 0.0,
        label: 'Reference Altitude (m)',
      },
    ],
    icon: 'ECEF→NED',
  },
  {
    type: 'ned_to_ecef',
    category: 'navigation',
    name: 'NED to ECEF',
    description: 'Convert NED coordinates to ECEF relative to reference point',
    inputs: [{ name: 'ned', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'ecef', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'referenceLat',
        type: 'number',
        default: 0.0,
        label: 'Reference Latitude (deg)',
      },
      {
        name: 'referenceLon',
        type: 'number',
        default: 0.0,
        label: 'Reference Longitude (deg)',
      },
      {
        name: 'referenceAlt',
        type: 'number',
        default: 0.0,
        label: 'Reference Altitude (m)',
      },
    ],
    icon: 'NED→ECEF',
  },
  // Waypoint Navigation
  {
    type: 'waypoint_follower',
    category: 'navigation',
    name: 'Waypoint Follower',
    description: 'Navigate through waypoints using great circle navigation',
    inputs: [{ name: 'currentLLA', dataType: 'double', dimensions: [3] }],
    outputs: [
      { name: 'heading', dataType: 'double', dimensions: [1] },
      { name: 'distance', dataType: 'double', dimensions: [1] },
      { name: 'waypointIndex', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 'waypoints',
        type: 'array',
        default: [[0, 0, 0], [1, 1, 0]],
        label: 'Waypoints [lat, lon, alt]',
        description: 'Array of waypoint coordinates in degrees and meters',
      },
      {
        name: 'captureRadius',
        type: 'number',
        default: 100.0,
        label: 'Capture Radius (m)',
        min: 0,
      },
    ],
    icon: 'WP',
  },
  {
    type: 'great_circle_distance',
    category: 'navigation',
    name: 'Great Circle Distance',
    description: 'Calculate great circle distance between two points using Haversine formula',
    inputs: [
      { name: 'point1', dataType: 'double', dimensions: [2] },
      { name: 'point2', dataType: 'double', dimensions: [2] },
    ],
    outputs: [{ name: 'distance', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'GCD',
  },
  {
    type: 'flat_earth_position',
    category: 'navigation',
    name: 'Flat Earth Position',
    description: 'Convert geodetic to local flat-earth coordinates',
    inputs: [{ name: 'lla', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'xyz', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'referenceLat',
        type: 'number',
        default: 0.0,
        label: 'Reference Latitude (deg)',
      },
      {
        name: 'referenceLon',
        type: 'number',
        default: 0.0,
        label: 'Reference Longitude (deg)',
      },
      {
        name: 'referenceAlt',
        type: 'number',
        default: 0.0,
        label: 'Reference Altitude (m)',
      },
    ],
    icon: 'FE',
  },
]
