import type { BlockDefinition } from '../types/block'

export const nonlinearBlocks: BlockDefinition[] = [
  {
    type: 'lookup_table_1d',
    category: 'nonlinear',
    name: '1-D Lookup Table',
    description: '1D lookup table with linear interpolation',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'xData',
        type: 'array',
        default: [0, 1, 2, 3],
        label: 'X Data (Breakpoints)',
        description: 'Input breakpoint values',
      },
      {
        name: 'yData',
        type: 'array',
        default: [0, 1, 4, 9],
        label: 'Y Data (Table)',
        description: 'Output table values',
      },
    ],
    icon: 'f(x)',
  },
  {
    type: 'lookup_table_2d',
    category: 'nonlinear',
    name: '2-D Lookup Table',
    description: '2D lookup table with bilinear interpolation',
    inputs: [
      { name: 'x', dataType: 'double', dimensions: [1] },
      { name: 'y', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'xData',
        type: 'array',
        default: [0, 1],
        label: 'Row Breakpoints',
        description: 'X-axis breakpoint values',
      },
      {
        name: 'yData',
        type: 'array',
        default: [0, 1],
        label: 'Column Breakpoints',
        description: 'Y-axis breakpoint values',
      },
      {
        name: 'zData',
        type: 'array',
        default: [[0, 0], [0, 1]],
        label: 'Table Data',
        description: '2D table data array',
      },
    ],
    icon: 'f(x,y)',
  },
  {
    type: 'quantizer',
    category: 'nonlinear',
    name: 'Quantizer',
    description: 'Rounds signal to discrete levels',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'interval',
        type: 'number',
        default: 1.0,
        label: 'Quantization Interval',
        description: 'Size of each quantization step',
        min: 0.001,
      },
    ],
    icon: '|||',
  },
  {
    type: 'relay',
    category: 'nonlinear',
    name: 'Relay',
    description: 'On/off switch with hysteresis',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'switchOn',
        type: 'number',
        default: 0.5,
        label: 'Switch On Point',
        description: 'Input value to switch on',
      },
      {
        name: 'switchOff',
        type: 'number',
        default: -0.5,
        label: 'Switch Off Point',
        description: 'Input value to switch off',
      },
      {
        name: 'outputOn',
        type: 'number',
        default: 1.0,
        label: 'Output When On',
        description: 'Output value in on state',
      },
      {
        name: 'outputOff',
        type: 'number',
        default: 0.0,
        label: 'Output When Off',
        description: 'Output value in off state',
      },
    ],
    icon: '~|',
  },
  {
    type: 'coulomb_friction',
    category: 'nonlinear',
    name: 'Coulomb Friction',
    description: 'Models static and dynamic friction',
    inputs: [{ name: 'velocity', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'friction', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'staticGain',
        type: 'number',
        default: 1.0,
        label: 'Static Friction',
        description: 'Static friction coefficient',
        min: 0,
      },
      {
        name: 'dynamicGain',
        type: 'number',
        default: 0.8,
        label: 'Dynamic Friction',
        description: 'Dynamic friction coefficient',
        min: 0,
      },
      {
        name: 'velocityThreshold',
        type: 'number',
        default: 0.01,
        label: 'Velocity Threshold',
        description: 'Threshold for static/dynamic transition',
        min: 0.001,
      },
    ],
    icon: 'Fr',
  },
  {
    type: 'variable_transport_delay',
    category: 'nonlinear',
    name: 'Variable Transport Delay',
    description: 'Delays signal by variable time',
    inputs: [
      { name: 'signal', dataType: 'double', dimensions: [1] },
      { name: 'delay', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'maxDelay',
        type: 'number',
        default: 1.0,
        label: 'Maximum Delay (s)',
        description: 'Maximum allowed delay time',
        min: 0.001,
      },
      {
        name: 'initialDelay',
        type: 'number',
        default: 0.1,
        label: 'Initial Delay (s)',
        description: 'Initial delay value',
        min: 0,
      },
    ],
    icon: 'Td',
  },
]
