import type { BlockDefinition } from '../types/block'

export const observerBlocks: BlockDefinition[] = [
  {
    type: 'luenberger_observer',
    category: 'observers',
    name: 'Luenberger Observer',
    description: 'State observer for linear systems',
    inputs: [
      { name: 'u', dataType: 'double', dimensions: [1] },
      { name: 'y', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'x_hat', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'A',
        type: 'array',
        default: [[0]],
        label: 'A Matrix',
        description: 'System state matrix',
      },
      {
        name: 'B',
        type: 'array',
        default: [[1]],
        label: 'B Matrix',
        description: 'Input matrix',
      },
      {
        name: 'C',
        type: 'array',
        default: [[1]],
        label: 'C Matrix',
        description: 'Output matrix',
      },
      {
        name: 'L',
        type: 'array',
        default: [[1]],
        label: 'L Matrix (Observer Gain)',
        description: 'Observer gain matrix for pole placement',
      },
      {
        name: 'initialState',
        type: 'array',
        default: [0],
        label: 'Initial State Estimate',
        description: 'Initial state estimate vector',
      },
    ],
    icon: 'L',
  },
  {
    type: 'kalman_filter',
    category: 'observers',
    name: 'Kalman Filter',
    description: 'Optimal state estimator with noise',
    inputs: [
      { name: 'u', dataType: 'double', dimensions: [1] },
      { name: 'y', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'x_hat', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'A',
        type: 'array',
        default: [[1]],
        label: 'A Matrix',
        description: 'State transition matrix (discrete)',
      },
      {
        name: 'B',
        type: 'array',
        default: [[1]],
        label: 'B Matrix',
        description: 'Input matrix',
      },
      {
        name: 'C',
        type: 'array',
        default: [[1]],
        label: 'C Matrix',
        description: 'Output/measurement matrix',
      },
      {
        name: 'Q',
        type: 'array',
        default: [[0.01]],
        label: 'Q Matrix (Process Noise)',
        description: 'Process noise covariance',
      },
      {
        name: 'R',
        type: 'array',
        default: [[0.1]],
        label: 'R Matrix (Measurement Noise)',
        description: 'Measurement noise covariance',
      },
      {
        name: 'initialState',
        type: 'array',
        default: [0],
        label: 'Initial State Estimate',
        description: 'Initial state estimate vector',
      },
      {
        name: 'initialP',
        type: 'array',
        default: [[1]],
        label: 'Initial Covariance',
        description: 'Initial error covariance matrix',
      },
    ],
    icon: 'KF',
  },
  {
    type: 'extended_kalman_filter',
    category: 'observers',
    name: 'Extended Kalman Filter',
    description: 'Kalman filter for nonlinear systems',
    inputs: [
      { name: 'u', dataType: 'double', dimensions: [1] },
      { name: 'y', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'x_hat', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'nStates',
        type: 'number',
        default: 1,
        label: 'Number of States',
        description: 'Dimension of state vector',
        min: 1,
      },
      {
        name: 'Q',
        type: 'array',
        default: [[0.01]],
        label: 'Q Matrix (Process Noise)',
        description: 'Process noise covariance',
      },
      {
        name: 'R',
        type: 'array',
        default: [[0.1]],
        label: 'R Matrix (Measurement Noise)',
        description: 'Measurement noise covariance',
      },
      {
        name: 'initialState',
        type: 'array',
        default: [0],
        label: 'Initial State Estimate',
        description: 'Initial state estimate vector',
      },
    ],
    icon: 'EKF',
  },
]
