import type { BlockDefinition } from '../types/block'

export const rfBlocks: BlockDefinition[] = [
  // Active Components
  {
    type: 'rf_amplifier',
    category: 'rf',
    name: 'RF Amplifier',
    description: 'RF amplifier with gain, noise figure, and compression modeling',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'gainDb',
        type: 'number',
        default: 20.0,
        label: 'Gain (dB)',
      },
      {
        name: 'noiseFigureDb',
        type: 'number',
        default: 3.0,
        label: 'Noise Figure (dB)',
        min: 0,
      },
      {
        name: 'p1dbDbm',
        type: 'number',
        default: 30.0,
        label: 'P1dB (dBm)',
        description: '1dB compression point',
      },
      {
        name: 'oip3Dbm',
        type: 'number',
        default: 40.0,
        label: 'OIP3 (dBm)',
        description: 'Output third-order intercept point',
      },
    ],
    icon: 'Amp',
  },
  {
    type: 'rf_mixer',
    category: 'rf',
    name: 'RF Mixer',
    description: 'RF frequency mixer for up/down conversion',
    inputs: [
      { name: 'rf', dataType: 'double', dimensions: [1] },
      { name: 'lo', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'if', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'conversionLossDb',
        type: 'number',
        default: 6.0,
        label: 'Conversion Loss (dB)',
      },
      {
        name: 'noiseFigureDb',
        type: 'number',
        default: 8.0,
        label: 'Noise Figure (dB)',
      },
      {
        name: 'loIsolationDb',
        type: 'number',
        default: 30.0,
        label: 'LO Isolation (dB)',
      },
    ],
    icon: 'Mix',
  },
  // Passive Components
  {
    type: 'rf_filter',
    category: 'rf',
    name: 'RF Filter',
    description: 'RF bandpass/lowpass/highpass filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'filterType',
        type: 'select',
        default: 'bandpass',
        label: 'Filter Type',
        options: [
          { value: 'lowpass', label: 'Lowpass' },
          { value: 'highpass', label: 'Highpass' },
          { value: 'bandpass', label: 'Bandpass' },
        ],
      },
      {
        name: 'centerFreqHz',
        type: 'number',
        default: 1e9,
        label: 'Center Frequency (Hz)',
        min: 0,
      },
      {
        name: 'bandwidthHz',
        type: 'number',
        default: 100e6,
        label: 'Bandwidth (Hz)',
        min: 0,
      },
      {
        name: 'insertionLossDb',
        type: 'number',
        default: 1.0,
        label: 'Insertion Loss (dB)',
        min: 0,
      },
    ],
    icon: 'Flt',
  },
  {
    type: 'attenuator',
    category: 'rf',
    name: 'Attenuator',
    description: 'Fixed or variable RF attenuator',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'attenuationDb',
        type: 'number',
        default: 10.0,
        label: 'Attenuation (dB)',
        min: 0,
      },
    ],
    icon: 'Att',
  },
  // S-Parameter and Budget
  {
    type: 's_parameter_network',
    category: 'rf',
    name: 'S-Parameter Network',
    description: '2-port network defined by S-parameters',
    inputs: [
      { name: 'a1', dataType: 'double', dimensions: [1] },
      { name: 'a2', dataType: 'double', dimensions: [1] },
    ],
    outputs: [
      { name: 'b1', dataType: 'double', dimensions: [1] },
      { name: 'b2', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 's11Mag',
        type: 'number',
        default: 0.1,
        label: 'S11 Magnitude',
      },
      {
        name: 's11Phase',
        type: 'number',
        default: 0.0,
        label: 'S11 Phase (deg)',
      },
      {
        name: 's21Mag',
        type: 'number',
        default: 10.0,
        label: 'S21 Magnitude',
      },
      {
        name: 's21Phase',
        type: 'number',
        default: 0.0,
        label: 'S21 Phase (deg)',
      },
      {
        name: 's12Mag',
        type: 'number',
        default: 0.01,
        label: 'S12 Magnitude',
      },
      {
        name: 's12Phase',
        type: 'number',
        default: 0.0,
        label: 'S12 Phase (deg)',
      },
      {
        name: 's22Mag',
        type: 'number',
        default: 0.1,
        label: 'S22 Magnitude',
      },
      {
        name: 's22Phase',
        type: 'number',
        default: 0.0,
        label: 'S22 Phase (deg)',
      },
    ],
    icon: 'S',
  },
  {
    type: 'rf_budget_element',
    category: 'rf',
    name: 'RF Budget Element',
    description: 'Cascaded RF budget analysis element',
    inputs: [
      { name: 'powerDbm', dataType: 'double', dimensions: [1] },
      { name: 'nfDb', dataType: 'double', dimensions: [1] },
    ],
    outputs: [
      { name: 'powerOutDbm', dataType: 'double', dimensions: [1] },
      { name: 'nfOutDb', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 'gainDb',
        type: 'number',
        default: 10.0,
        label: 'Gain (dB)',
      },
      {
        name: 'noiseFigureDb',
        type: 'number',
        default: 3.0,
        label: 'Noise Figure (dB)',
        min: 0,
      },
    ],
    icon: 'BUD',
  },
  // Modulators
  {
    type: 'am_modulator',
    category: 'rf',
    name: 'AM Modulator',
    description: 'Amplitude modulation',
    inputs: [
      { name: 'message', dataType: 'double', dimensions: [1] },
      { name: 'carrier', dataType: 'double', dimensions: [1] },
    ],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'modulationIndex',
        type: 'number',
        default: 1.0,
        label: 'Modulation Index',
        min: 0,
        max: 1,
      },
    ],
    icon: 'AM',
  },
  {
    type: 'fm_modulator',
    category: 'rf',
    name: 'FM Modulator',
    description: 'Frequency modulation',
    inputs: [{ name: 'message', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'carrierFreqHz',
        type: 'number',
        default: 1e6,
        label: 'Carrier Frequency (Hz)',
        min: 0,
      },
      {
        name: 'freqDeviationHz',
        type: 'number',
        default: 75e3,
        label: 'Frequency Deviation (Hz)',
        min: 0,
      },
      {
        name: 'amplitude',
        type: 'number',
        default: 1.0,
        label: 'Carrier Amplitude',
        min: 0,
      },
    ],
    icon: 'FM',
  },
  {
    type: 'phase_noise',
    category: 'rf',
    name: 'Phase Noise',
    description: 'Add phase noise to signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'phaseNoiseDbcHz',
        type: 'number',
        default: -100.0,
        label: 'Phase Noise (dBc/Hz)',
        description: 'Single-sideband phase noise density',
      },
      {
        name: 'offsetFreqHz',
        type: 'number',
        default: 10e3,
        label: 'Offset Frequency (Hz)',
      },
    ],
    icon: 'φn',
  },
  // Power Conversions
  {
    type: 'dbm_to_watts',
    category: 'rf',
    name: 'dBm to Watts',
    description: 'Convert power from dBm to Watts',
    inputs: [{ name: 'dBm', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'W', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'dBm→W',
  },
  {
    type: 'watts_to_dbm',
    category: 'rf',
    name: 'Watts to dBm',
    description: 'Convert power from Watts to dBm',
    inputs: [{ name: 'W', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'dBm', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: 'W→dBm',
  },
]
