import type { BlockDefinition } from '../types/block'

export const sensorFusionBlocks: BlockDefinition[] = [
  // Sensor Models
  {
    type: 'imu_sensor',
    category: 'sensor_fusion',
    name: 'IMU Sensor',
    description: 'Inertial Measurement Unit with accelerometer and gyroscope',
    inputs: [
      { name: 'trueAccel', dataType: 'double', dimensions: [3] },
      { name: 'trueGyro', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'imuData', dataType: 'double', dimensions: [6] }],
    parameters: [
      {
        name: 'accelNoise',
        type: 'number',
        default: 0.01,
        label: 'Accelerometer Noise (m/s^2)',
        min: 0,
      },
      {
        name: 'gyroNoise',
        type: 'number',
        default: 0.001,
        label: 'Gyroscope Noise (rad/s)',
        min: 0,
      },
      {
        name: 'accelBias',
        type: 'array',
        default: [0, 0, 0],
        label: 'Accelerometer Bias [x, y, z]',
      },
      {
        name: 'gyroBias',
        type: 'array',
        default: [0, 0, 0],
        label: 'Gyroscope Bias [x, y, z]',
      },
      {
        name: 'seed',
        type: 'number',
        default: 0,
        label: 'Random Seed (0 = random)',
        description: 'Seed for reproducible noise',
      },
    ],
    icon: 'IMU',
  },
  {
    type: 'accelerometer',
    category: 'sensor_fusion',
    name: 'Accelerometer',
    description: 'Three-axis accelerometer sensor model',
    inputs: [{ name: 'trueAccel', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'measuredAccel', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'noise',
        type: 'number',
        default: 0.01,
        label: 'Noise (m/s^2)',
        min: 0,
      },
      {
        name: 'bias',
        type: 'array',
        default: [0, 0, 0],
        label: 'Bias [x, y, z]',
      },
    ],
    icon: 'Acc',
  },
  {
    type: 'gyroscope',
    category: 'sensor_fusion',
    name: 'Gyroscope',
    description: 'Three-axis gyroscope sensor model',
    inputs: [{ name: 'trueGyro', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'measuredGyro', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'noise',
        type: 'number',
        default: 0.001,
        label: 'Noise (rad/s)',
        min: 0,
      },
      {
        name: 'bias',
        type: 'array',
        default: [0, 0, 0],
        label: 'Bias [x, y, z]',
      },
    ],
    icon: 'Gyro',
  },
  {
    type: 'magnetometer',
    category: 'sensor_fusion',
    name: 'Magnetometer',
    description: 'Three-axis magnetometer sensor model',
    inputs: [{ name: 'trueMag', dataType: 'double', dimensions: [3] }],
    outputs: [{ name: 'measuredMag', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'noise',
        type: 'number',
        default: 0.01,
        label: 'Noise (Gauss)',
        min: 0,
      },
      {
        name: 'bias',
        type: 'array',
        default: [0, 0, 0],
        label: 'Hard Iron Bias [x, y, z]',
      },
    ],
    icon: 'Mag',
  },
  {
    type: 'gps_sensor',
    category: 'sensor_fusion',
    name: 'GPS Sensor',
    description: 'GPS receiver model with position and velocity',
    inputs: [
      { name: 'truePosition', dataType: 'double', dimensions: [3] },
      { name: 'trueVelocity', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'gpsData', dataType: 'double', dimensions: [6] }],
    parameters: [
      {
        name: 'positionNoise',
        type: 'number',
        default: 5.0,
        label: 'Position Noise (m)',
        min: 0,
      },
      {
        name: 'velocityNoise',
        type: 'number',
        default: 0.1,
        label: 'Velocity Noise (m/s)',
        min: 0,
      },
      {
        name: 'updateRate',
        type: 'number',
        default: 10.0,
        label: 'Update Rate (Hz)',
        min: 0.1,
      },
      {
        name: 'seed',
        type: 'number',
        default: 0,
        label: 'Random Seed (0 = random)',
      },
    ],
    icon: 'GPS',
  },
  {
    type: 'altimeter',
    category: 'sensor_fusion',
    name: 'Altimeter',
    description: 'Barometric or radar altimeter sensor model',
    inputs: [{ name: 'trueAltitude', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'measuredAltitude', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'noise',
        type: 'number',
        default: 1.0,
        label: 'Noise (m)',
        min: 0,
      },
      {
        name: 'bias',
        type: 'number',
        default: 0.0,
        label: 'Bias (m)',
      },
    ],
    icon: 'Alt',
  },
  // Attitude Estimation Filters
  {
    type: 'complementary_filter',
    category: 'sensor_fusion',
    name: 'Complementary Filter',
    description: 'Fuse accelerometer and gyroscope for attitude estimation',
    inputs: [
      { name: 'accel', dataType: 'double', dimensions: [3] },
      { name: 'gyro', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'euler', dataType: 'double', dimensions: [3] }],
    parameters: [
      {
        name: 'alpha',
        type: 'number',
        default: 0.98,
        label: 'Alpha (gyro weight)',
        description: 'Higher values trust gyroscope more (0-1)',
        min: 0,
        max: 1,
      },
    ],
    icon: 'CF',
  },
  {
    type: 'madgwick_filter',
    category: 'sensor_fusion',
    name: 'Madgwick Filter',
    description: 'Gradient descent AHRS/IMU sensor fusion',
    inputs: [
      { name: 'accel', dataType: 'double', dimensions: [3] },
      { name: 'gyro', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'quaternion', dataType: 'double', dimensions: [4] }],
    parameters: [
      {
        name: 'beta',
        type: 'number',
        default: 0.1,
        label: 'Beta (filter gain)',
        description: 'Higher values = faster convergence, more noise sensitivity',
        min: 0,
      },
    ],
    icon: 'Mad',
  },
  {
    type: 'mahony_filter',
    category: 'sensor_fusion',
    name: 'Mahony Filter',
    description: 'Proportional-integral AHRS filter',
    inputs: [
      { name: 'accel', dataType: 'double', dimensions: [3] },
      { name: 'gyro', dataType: 'double', dimensions: [3] },
    ],
    outputs: [{ name: 'quaternion', dataType: 'double', dimensions: [4] }],
    parameters: [
      {
        name: 'Kp',
        type: 'number',
        default: 1.0,
        label: 'Kp (proportional gain)',
        min: 0,
      },
      {
        name: 'Ki',
        type: 'number',
        default: 0.0,
        label: 'Ki (integral gain)',
        min: 0,
      },
    ],
    icon: 'Mah',
  },
  // Navigation Fusion
  {
    type: 'ins_gps_fusion',
    category: 'sensor_fusion',
    name: 'INS/GPS Fusion',
    description: 'Loosely coupled INS/GPS navigation filter',
    inputs: [
      { name: 'imu', dataType: 'double', dimensions: [6] },
      { name: 'gpsPos', dataType: 'double', dimensions: [3] },
      { name: 'gpsVel', dataType: 'double', dimensions: [3] },
    ],
    outputs: [
      { name: 'position', dataType: 'double', dimensions: [3] },
      { name: 'velocity', dataType: 'double', dimensions: [3] },
      { name: 'attitude', dataType: 'double', dimensions: [3] },
    ],
    parameters: [
      {
        name: 'initialPosition',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Position [lat, lon, alt]',
      },
      {
        name: 'initialVelocity',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Velocity [N, E, D]',
      },
      {
        name: 'initialAttitude',
        type: 'array',
        default: [0, 0, 0],
        label: 'Initial Attitude [roll, pitch, yaw]',
      },
    ],
    icon: 'INS/GPS',
  },
  // Tracking Filters
  {
    type: 'alpha_beta_filter',
    category: 'sensor_fusion',
    name: 'Alpha-Beta Filter',
    description: 'Simple tracking filter for position and velocity',
    inputs: [{ name: 'measurement', dataType: 'double', dimensions: [1] }],
    outputs: [
      { name: 'position', dataType: 'double', dimensions: [1] },
      { name: 'velocity', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 'alpha',
        type: 'number',
        default: 0.5,
        label: 'Alpha (position gain)',
        min: 0,
        max: 1,
      },
      {
        name: 'beta',
        type: 'number',
        default: 0.1,
        label: 'Beta (velocity gain)',
        min: 0,
        max: 1,
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time (s)',
        min: 0.001,
      },
    ],
    icon: 'αβ',
  },
  {
    type: 'alpha_beta_gamma_filter',
    category: 'sensor_fusion',
    name: 'Alpha-Beta-Gamma Filter',
    description: 'Tracking filter for position, velocity, and acceleration',
    inputs: [{ name: 'measurement', dataType: 'double', dimensions: [1] }],
    outputs: [
      { name: 'position', dataType: 'double', dimensions: [1] },
      { name: 'velocity', dataType: 'double', dimensions: [1] },
      { name: 'acceleration', dataType: 'double', dimensions: [1] },
    ],
    parameters: [
      {
        name: 'alpha',
        type: 'number',
        default: 0.9,
        label: 'Alpha (position gain)',
        min: 0,
        max: 1,
      },
      {
        name: 'beta',
        type: 'number',
        default: 0.5,
        label: 'Beta (velocity gain)',
        min: 0,
        max: 1,
      },
      {
        name: 'gamma',
        type: 'number',
        default: 0.1,
        label: 'Gamma (acceleration gain)',
        min: 0,
        max: 1,
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0.1,
        label: 'Sample Time (s)',
        min: 0.001,
      },
    ],
    icon: 'αβγ',
  },
]
