import type { BlockDefinition } from '../types/block'

export const signalProcessingBlocks: BlockDefinition[] = [
  {
    type: 'rate_limiter',
    category: 'signal_processing',
    name: 'Rate Limiter',
    description: 'Limits the rate of change of a signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'risingLimit',
        type: 'number',
        default: 1.0,
        label: 'Rising Slew Rate',
        description: 'Maximum rate of increase per second',
      },
      {
        name: 'fallingLimit',
        type: 'number',
        default: -1.0,
        label: 'Falling Slew Rate',
        description: 'Maximum rate of decrease per second (negative)',
      },
    ],
    icon: '/',
  },
  {
    type: 'moving_average',
    category: 'signal_processing',
    name: 'Moving Average',
    description: 'Calculates moving average of input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'windowSize',
        type: 'number',
        default: 10,
        label: 'Window Size',
        description: 'Number of samples for averaging',
        min: 1,
      },
    ],
    icon: 'AVG',
  },
  {
    type: 'low_pass_filter',
    category: 'signal_processing',
    name: 'Low-Pass Filter',
    description: 'First-order low-pass filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'cutoffFrequency',
        type: 'number',
        default: 10.0,
        label: 'Cutoff Frequency (Hz)',
        description: 'Filter cutoff frequency in Hz',
        min: 0.001,
      },
    ],
    icon: 'LPF',
  },
  {
    type: 'high_pass_filter',
    category: 'signal_processing',
    name: 'High-Pass Filter',
    description: 'First-order high-pass filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'cutoffFrequency',
        type: 'number',
        default: 10.0,
        label: 'Cutoff Frequency (Hz)',
        description: 'Filter cutoff frequency in Hz',
        min: 0.001,
      },
    ],
    icon: 'HPF',
  },
  {
    type: 'band_pass_filter',
    category: 'signal_processing',
    name: 'Band-Pass Filter',
    description: 'Band-pass filter combining low and high-pass',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'lowCutoff',
        type: 'number',
        default: 1.0,
        label: 'Low Cutoff (Hz)',
        description: 'Lower cutoff frequency in Hz',
        min: 0.001,
      },
      {
        name: 'highCutoff',
        type: 'number',
        default: 100.0,
        label: 'High Cutoff (Hz)',
        description: 'Upper cutoff frequency in Hz',
        min: 0.001,
      },
    ],
    icon: 'BPF',
  },
  {
    type: 'backlash',
    category: 'signal_processing',
    name: 'Backlash',
    description: 'Models mechanical backlash/play in gears',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'deadbandWidth',
        type: 'number',
        default: 1.0,
        label: 'Deadband Width',
        description: 'Total width of the deadband',
        min: 0,
      },
      {
        name: 'initialOutput',
        type: 'number',
        default: 0.0,
        label: 'Initial Output',
        description: 'Initial output value',
      },
    ],
    icon: '><',
  },
]
