import type { BlockDefinition } from '../types/block'

export const signalProcessingBlocks: BlockDefinition[] = [
  {
    type: 'rate_limiter',
    category: 'signal_processing',
    name: 'Rate Limiter',
    description: 'Limits the rate of change of a signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'risingLimit',
        type: 'number',
        default: 1.0,
        label: 'Rising Slew Rate',
        description: 'Maximum rate of increase per second',
      },
      {
        name: 'fallingLimit',
        type: 'number',
        default: -1.0,
        label: 'Falling Slew Rate',
        description: 'Maximum rate of decrease per second (negative)',
      },
    ],
    icon: '/',
  },
  {
    type: 'moving_average',
    category: 'signal_processing',
    name: 'Moving Average',
    description: 'Calculates moving average of input signal',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'windowSize',
        type: 'number',
        default: 10,
        label: 'Window Size',
        description: 'Number of samples for averaging',
        min: 1,
      },
    ],
    icon: 'AVG',
  },
  {
    type: 'low_pass_filter',
    category: 'signal_processing',
    name: 'Low-Pass Filter',
    description: 'First-order low-pass filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'cutoffFrequency',
        type: 'number',
        default: 10.0,
        label: 'Cutoff Frequency (Hz)',
        description: 'Filter cutoff frequency in Hz',
        min: 0.001,
      },
    ],
    icon: 'LPF',
  },
  {
    type: 'high_pass_filter',
    category: 'signal_processing',
    name: 'High-Pass Filter',
    description: 'First-order high-pass filter',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'cutoffFrequency',
        type: 'number',
        default: 10.0,
        label: 'Cutoff Frequency (Hz)',
        description: 'Filter cutoff frequency in Hz',
        min: 0.001,
      },
    ],
    icon: 'HPF',
  },
  {
    type: 'band_pass_filter',
    category: 'signal_processing',
    name: 'Band-Pass Filter',
    description: 'Band-pass filter combining low and high-pass',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'lowCutoff',
        type: 'number',
        default: 1.0,
        label: 'Low Cutoff (Hz)',
        description: 'Lower cutoff frequency in Hz',
        min: 0.001,
      },
      {
        name: 'highCutoff',
        type: 'number',
        default: 100.0,
        label: 'High Cutoff (Hz)',
        description: 'Upper cutoff frequency in Hz',
        min: 0.001,
      },
    ],
    icon: 'BPF',
  },
  {
    type: 'analog_filter',
    category: 'signal_processing',
    name: 'Analog Filter',
    description:
      'Configurable IIR filter with Butterworth, Chebyshev, and Bessel designs',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'design',
        type: 'select',
        default: 'butterworth',
        label: 'Design Method',
        description: 'Filter design algorithm',
        options: [
          { value: 'butterworth', label: 'Butterworth' },
          { value: 'chebyshev1', label: 'Chebyshev I' },
          { value: 'chebyshev2', label: 'Chebyshev II' },
          { value: 'bessel', label: 'Bessel' },
        ],
      },
      {
        name: 'response',
        type: 'select',
        default: 'lowpass',
        label: 'Response Type',
        description: 'Filter response type',
        options: [
          { value: 'lowpass', label: 'Low-Pass' },
          { value: 'highpass', label: 'High-Pass' },
          { value: 'bandpass', label: 'Band-Pass' },
          { value: 'bandstop', label: 'Band-Stop' },
        ],
      },
      {
        name: 'order',
        type: 'number',
        default: 2,
        label: 'Filter Order',
        description: 'Order of the filter (1-10)',
        min: 1,
        max: 10,
      },
      {
        name: 'cutoffFrequency',
        type: 'number',
        default: 10.0,
        label: 'Cutoff Frequency (Hz)',
        description: 'Cutoff frequency for lowpass/highpass',
        min: 0.001,
      },
      {
        name: 'lowCutoff',
        type: 'number',
        default: 1.0,
        label: 'Low Cutoff (Hz)',
        description: 'Lower cutoff for bandpass/bandstop',
        min: 0.001,
      },
      {
        name: 'highCutoff',
        type: 'number',
        default: 10.0,
        label: 'High Cutoff (Hz)',
        description: 'Upper cutoff for bandpass/bandstop',
        min: 0.001,
      },
      {
        name: 'passbandRipple',
        type: 'number',
        default: 1.0,
        label: 'Passband Ripple (dB)',
        description: 'Ripple in passband for Chebyshev I',
        min: 0.01,
      },
      {
        name: 'stopbandAtten',
        type: 'number',
        default: 40.0,
        label: 'Stopband Atten (dB)',
        description: 'Attenuation in stopband for Chebyshev II',
        min: 1.0,
      },
    ],
    icon: 'Σ',
  },
  {
    type: 'notch_filter',
    category: 'signal_processing',
    name: 'Notch Filter',
    description: 'Rejects a specific frequency (e.g., 50/60 Hz line noise)',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'notchFrequency',
        type: 'number',
        default: 60.0,
        label: 'Notch Frequency (Hz)',
        description: 'Center frequency to reject',
        min: 0.001,
      },
      {
        name: 'bandwidth',
        type: 'number',
        default: 2.0,
        label: 'Bandwidth (Hz)',
        description: 'Width of the notch (3 dB bandwidth)',
        min: 0.01,
      },
      {
        name: 'depth',
        type: 'number',
        default: 40.0,
        label: 'Notch Depth (dB)',
        description: 'Attenuation at notch frequency',
        min: 1.0,
      },
    ],
    icon: 'N',
  },
  {
    type: 'backlash',
    category: 'signal_processing',
    name: 'Backlash',
    description: 'Models mechanical backlash/play in gears',
    inputs: [{ name: 'in', dataType: 'double', dimensions: [1] }],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'deadbandWidth',
        type: 'number',
        default: 1.0,
        label: 'Deadband Width',
        description: 'Total width of the deadband',
        min: 0,
      },
      {
        name: 'initialOutput',
        type: 'number',
        default: 0.0,
        label: 'Initial Output',
        description: 'Initial output value',
      },
    ],
    icon: '><',
  },
]
