import type { BlockDefinition } from '../types/block'

export const sourceBlocks: BlockDefinition[] = [
  {
    type: 'constant',
    category: 'sources',
    name: 'Constant',
    description: 'Output a constant value',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'value',
        type: 'string', // String to support both numbers and expressions like eye(4)
        default: '1',
        label: 'Constant Value',
        description: 'The constant output value (number or expression)',
      },
    ],
    icon: '1',
  },
  {
    type: 'step',
    category: 'sources',
    name: 'Step',
    description: 'Output a step signal',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'stepTime',
        type: 'number',
        default: 1,
        label: 'Step Time',
        description: 'Time of step transition',
      },
      {
        name: 'initialValue',
        type: 'number',
        default: 0,
        label: 'Initial Value',
        description: 'Output before step time',
      },
      {
        name: 'finalValue',
        type: 'number',
        default: 1,
        label: 'Final Value',
        description: 'Output after step time',
      },
    ],
    icon: '⌐',
  },
  {
    type: 'ramp',
    category: 'sources',
    name: 'Ramp',
    description: 'Output a ramp signal',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'slope',
        type: 'number',
        default: 1,
        label: 'Slope',
        description: 'Rate of change',
      },
      {
        name: 'startTime',
        type: 'number',
        default: 0,
        label: 'Start Time',
        description: 'Time when ramp begins',
      },
      {
        name: 'initialOutput',
        type: 'number',
        default: 0,
        label: 'Initial Output',
        description: 'Output before start time',
      },
    ],
    icon: '/',
  },
  {
    type: 'sine_wave',
    category: 'sources',
    name: 'Sine Wave',
    description: 'Output a sinusoidal signal',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'amplitude',
        type: 'number',
        default: 1,
        label: 'Amplitude',
        description: 'Peak amplitude',
      },
      {
        name: 'frequency',
        type: 'number',
        default: 1,
        label: 'Frequency (Hz)',
        description: 'Frequency in Hertz',
      },
      {
        name: 'phase',
        type: 'number',
        default: 0,
        label: 'Phase (rad)',
        description: 'Phase offset in radians',
      },
      {
        name: 'bias',
        type: 'number',
        default: 0,
        label: 'Bias',
        description: 'DC offset',
      },
    ],
    icon: '∿',
  },
  {
    type: 'pulse_generator',
    category: 'sources',
    name: 'Pulse Generator',
    description: 'Output a pulse train',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'amplitude',
        type: 'number',
        default: 1,
        label: 'Amplitude',
        description: 'Pulse amplitude',
      },
      {
        name: 'period',
        type: 'number',
        default: 1,
        label: 'Period (s)',
        description: 'Pulse period in seconds',
      },
      {
        name: 'dutyCycle',
        type: 'number',
        default: 50,
        label: 'Duty Cycle (%)',
        description: 'Percentage of period at high level',
        min: 0,
        max: 100,
      },
      {
        name: 'phaseDelay',
        type: 'number',
        default: 0,
        label: 'Phase Delay (s)',
        description: 'Delay before first pulse',
      },
    ],
    icon: '⊓',
  },
  {
    type: 'clock',
    category: 'sources',
    name: 'Clock',
    description: 'Output simulation time',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [],
    icon: '⏱',
  },
  {
    type: 'white_noise',
    category: 'sources',
    name: 'White Noise',
    description: 'Additive White Gaussian Noise (AWGN) source',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'mean',
        type: 'number',
        default: 0,
        label: 'Mean',
        description: 'Mean value of the noise distribution',
      },
      {
        name: 'variance',
        type: 'number',
        default: 1,
        label: 'Variance',
        description: 'Variance (σ²) of the noise. Std dev = √variance',
      },
      {
        name: 'seed',
        type: 'number',
        default: null,
        label: 'Seed (optional)',
        description: 'Random seed for reproducibility. Leave empty for random.',
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0,
        label: 'Sample Time',
        description: 'Sample time for discrete noise. 0 = continuous.',
      },
    ],
    icon: '⌇',
  },
  {
    type: 'uniform_noise',
    category: 'sources',
    name: 'Uniform Noise',
    description: 'Uniform random noise source',
    inputs: [],
    outputs: [{ name: 'out', dataType: 'double', dimensions: [1] }],
    parameters: [
      {
        name: 'minimum',
        type: 'number',
        default: -1,
        label: 'Minimum',
        description: 'Minimum value of uniform distribution',
      },
      {
        name: 'maximum',
        type: 'number',
        default: 1,
        label: 'Maximum',
        description: 'Maximum value of uniform distribution',
      },
      {
        name: 'seed',
        type: 'number',
        default: null,
        label: 'Seed (optional)',
        description: 'Random seed for reproducibility. Leave empty for random.',
      },
      {
        name: 'sampleTime',
        type: 'number',
        default: 0,
        label: 'Sample Time',
        description: 'Sample time for discrete noise. 0 = continuous.',
      },
    ],
    icon: '⋈',
  },
]
