#!/usr/bin/env python3
"""End-to-end regressions for the browser-facing LibreSim stack."""

from __future__ import annotations

import json
import math
import os
import time
import unittest
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

BASE_URL = os.environ.get("LIBRESIM_GUI_URL", "http://127.0.0.1:4200").rstrip("/")


def api_request(
    path: str,
    *,
    method: str = "GET",
    body: dict[str, Any] | None = None,
) -> Any:
    data = None if body is None else json.dumps(body).encode("utf-8")
    request = urllib.request.Request(
        f"{BASE_URL}{path}",
        data=data,
        method=method,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise AssertionError(f"{method} {path} returned HTTP {error.code}: {detail}") from error


def editor_sine_scope_model() -> Any:
    """Return the model shape generated by adding and wiring blocks in the editor."""
    return {
        "id": "gui-sine-scope-regression",
        "metadata": {
            "name": "GUI Sine Scope Regression",
            "description": "",
            "author": "",
            "createdAt": "2026-01-01T00:00:00Z",
            "modifiedAt": "2026-01-01T00:00:00Z",
            "version": "1.0.0",
        },
        "blocks": [
            {
                "id": "sine-ui",
                "type": "sine_wave",
                "name": "Sine Wave",
                "position": {"x": 100, "y": 100},
                "parameters": {
                    "amplitude": 1,
                    "frequency": 1,
                    "phase": 0,
                    "bias": 0,
                },
                "inputPorts": [],
                "outputPorts": [
                    {
                        "id": "sine-ui-out-0",
                        "name": "out",
                        "dataType": "double",
                        "dimensions": [1],
                    }
                ],
            },
            {
                "id": "scope-ui",
                "type": "scope",
                "name": "Scope",
                "position": {"x": 350, "y": 100},
                "parameters": {"numInputs": 1, "sampleTime": -1},
                "inputPorts": [
                    {
                        "id": "scope-ui-in-0",
                        "name": "in",
                        "dataType": "double",
                        "dimensions": [1],
                    }
                ],
                "outputPorts": [],
            },
        ],
        "connections": [
            {
                "id": "sine-to-scope",
                "sourceBlockId": "sine-ui",
                "sourcePortId": "sine-ui-out-0",
                "targetBlockId": "scope-ui",
                "targetPortId": "scope-ui-in-0",
            }
        ],
        "simulationConfig": {
            "solver": "rk4",
            "startTime": 0,
            "stopTime": 1,
            "stepSize": 0.01,
        },
    }


class TestGuiStack(unittest.TestCase):
    def test_example_loads_through_frontend_proxy(self) -> None:
        model = api_request("/api/examples/01_sine_wave_basic")

        self.assertEqual(model["id"], "example-sine-wave-basic")
        self.assertTrue(model["blocks"])
        self.assertTrue(model["connections"])

    def test_editor_sine_wave_reaches_scope_through_frontend_proxy(self) -> None:
        model = editor_sine_scope_model()
        started = api_request(
            "/api/simulate/start",
            method="POST",
            body={"model": model, "config": model["simulationConfig"]},
        )
        session_id = started["sessionId"]
        query = urllib.parse.urlencode({"sessionId": session_id})

        deadline = time.monotonic() + 10
        while True:
            status = api_request(f"/api/simulate/status?{query}")
            if status["status"] in {"completed", "error"}:
                break
            if time.monotonic() >= deadline:
                self.fail(f"simulation did not finish: {status}")
            time.sleep(0.05)

        self.assertEqual(status["status"], "completed", status.get("error"))
        results = api_request(f"/api/simulate/results?{query}")
        scope_signal = next(
            signal for signal in results["signals"] if signal["blockId"] == "scope-ui"
        )

        self.assertGreater(len(scope_signal["times"]), 50)
        self.assertEqual(len(scope_signal["times"]), len(scope_signal["values"]))
        self.assertGreater(max(scope_signal["values"]), 0.9)
        self.assertLess(min(scope_signal["values"]), -0.9)
        for timestamp, value in zip(scope_signal["times"], scope_signal["values"], strict=True):
            self.assertAlmostEqual(value, math.sin(2 * math.pi * timestamp), places=9)


if __name__ == "__main__":
    unittest.main(verbosity=2)
