"""Python code generator."""

from typing import Any

from ..base import LanguageGenerator
from ...models import (
    Language,
    IntegrationMethod,
    GeneratedProject,
    CompiledModelInfo,
    BlockInfo,
)
from ...integration import IntegrationCodeGenerator
from .blocks import get_block_template, BLOCK_TEMPLATES


class PythonCodeGenerator(LanguageGenerator):
    """Generate Python simulation code."""

    def generate(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> GeneratedProject:
        """Generate a complete Python project."""
        project = GeneratedProject(
            name=config.project_name,
            language=Language.PYTHON,
        )

        # Generate blocks.py - all block class definitions
        blocks_code = self._generate_blocks_file(model_info)
        project.add_file("blocks.py", blocks_code)

        # Generate integration.py - integration methods
        integration_code = self.generate_integration_code(config.integration_method)
        project.add_file("integration.py", integration_code)

        # Generate simulation.py - main model class and step function
        simulation_code = self._generate_simulation_file(model_info, config)
        project.add_file("simulation.py", simulation_code)

        # Generate main.py - example runner
        if config.include_main:
            main_code = self.generate_main_code(model_info, config)
            project.add_file("main.py", main_code)

        # Generate requirements.txt
        requirements = self._generate_requirements()
        project.add_file("requirements.txt", requirements)

        # Generate setup.py
        setup_code = self._generate_setup(config)
        project.add_file("setup.py", setup_code)

        # Generate README.md
        readme = self._generate_readme(model_info, config)
        project.add_file("README.md", readme)

        # Validate generated Python code
        self._validate_python_code(project)

        return project

    def _validate_python_code(self, project: GeneratedProject) -> None:
        """Validate that generated Python code has no syntax errors.

        Raises:
            SyntaxError: If any Python file has syntax errors
        """
        for file in project.files:
            if file.path.endswith('.py'):
                try:
                    compile(file.content, file.path, 'exec')
                except SyntaxError as e:
                    # Add more context to the error
                    error_msg = (
                        f"Syntax error in generated {file.path}:\n"
                        f"  Line {e.lineno}: {e.text.strip() if e.text else '(no text)'}\n"
                        f"  Error: {e.msg}"
                    )
                    # Re-raise with better message
                    raise SyntaxError(error_msg) from e

    def generate_block_code(self, block: BlockInfo) -> str:
        """Generate code for a single block."""
        template = get_block_template(block.type)
        if template is None:
            # Fallback to passthrough
            return self._generate_passthrough_block(block)

        # Fill in template with block-specific values
        return template.format(
            id=self.sanitize_identifier(block.id),
            name=block.name,
            **block.parameters,
        )

    def generate_integration_code(self, method: IntegrationMethod) -> str:
        """Generate integration method code."""
        return f'''"""Integration methods for numerical simulation."""

{IntegrationCodeGenerator.generate_python_all()}
'''

    def generate_main_code(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate main entry point code."""
        csv_output = ""
        if config.include_csv_output:
            csv_output = '''
    # Write results to CSV
    with open('results.csv', 'w', newline='') as f:
        import csv
        writer = csv.writer(f)

        # Header
        header = ['time'] + list(results.keys())
        header.remove('time')
        writer.writerow(['time'] + [k for k in results.keys() if k != 'time'])

        # Data rows
        n_points = len(results['time'])
        for i in range(n_points):
            row = [results['time'][i]]
            for key in results:
                if key != 'time':
                    row.append(results[key][i])
            writer.writerow(row)

    print(f"Results written to results.csv ({n_points} data points)")
'''

        return f'''#!/usr/bin/env python3
"""Example simulation runner.

Generated by LibreSim Coder.
"""

from simulation import Model, run_simulation


def main():
    """Run the simulation and output results."""
    # Create model instance
    model = Model()

    # Run simulation
    print("Running simulation...")
    results = run_simulation(
        model,
        dt={config.step_size},
        t_end={config.stop_time},
        t_start={config.start_time},
        method="{config.integration_method.value}",
    )

    print(f"Simulation complete. {{len(results['time'])}} time steps.")
{csv_output}

if __name__ == "__main__":
    main()
'''

    def _generate_blocks_file(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.py with all block class definitions."""
        imports = '''"""Block class definitions.

Generated by LibreSim Coder.
"""

import math
from typing import Any, List, Optional

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False

'''
        classes = []

        # Generate a class for each block in the model
        for block in model_info.blocks:
            class_code = self._generate_block_class(block)
            classes.append(class_code)

        return imports + "\n\n".join(classes)

    def _generate_block_class(self, block: BlockInfo) -> str:
        """Generate a Python class for a block."""
        class_name = f"Block_{self.sanitize_identifier(block.id)}"
        var_name = self.get_block_var_name(block)

        # Get template for this block type
        template_func = BLOCK_TEMPLATES.get(block.type)
        if template_func:
            return template_func(block, class_name)

        # Default passthrough implementation
        return self._generate_passthrough_block(block)

    def _generate_passthrough_block(self, block: BlockInfo) -> str:
        """Generate a passthrough block (for unsupported types)."""
        class_name = f"Block_{self.sanitize_identifier(block.id)}"
        return f'''
class {class_name}:
    """Passthrough block: {block.name} (type: {block.type})"""

    def __init__(self):
        self.input = 0.0
        self.output = 0.0

    def init(self):
        self.output = 0.0

    def update(self, t: float):
        self.output = self.input

    def get_output(self, port: int = 0) -> float:
        return self.output
'''

    def _generate_simulation_file(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate simulation.py with Model class and run function."""
        # Build block instantiation code
        block_inits = []
        for block in model_info.blocks:
            class_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = self.get_block_var_name(block)
            block_inits.append(f"        self.{var_name} = {class_name}()")

        # Build connection wiring code
        connection_code = self._generate_connection_code(model_info)

        # Build update order code (8 spaces - inside method body)
        update_calls = []
        for block_id in model_info.execution_order:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block:
                var_name = self.get_block_var_name(block)
                update_calls.append(f"        self.{var_name}.update(t)")

        # Build integrator list for state propagation
        integrator_list = []
        for block_id in model_info.integrator_blocks:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block:
                var_name = self.get_block_var_name(block)
                integrator_list.append(f"self.{var_name}")

        # Build output recording code
        output_recording = self._generate_output_recording(model_info)

        return f'''"""Simulation model.

Generated by LibreSim Coder.
"""

from blocks import *
from integration import get_propagate_function, get_num_passes


class Model:
    """Simulation model containing all blocks and connections."""

    def __init__(self):
        # Instantiate all blocks
{chr(10).join(block_inits)}

        # List of integrator blocks for state propagation
        self._integrators = [{', '.join(integrator_list)}]

    def init(self):
        """Initialize all blocks."""
        for block in self._get_all_blocks():
            if hasattr(block, 'init'):
                block.init()

    def _get_all_blocks(self):
        """Get list of all block instances."""
        return [getattr(self, attr) for attr in dir(self)
                if attr.startswith('block_') and not callable(getattr(self, attr))]

    def wire_connections(self):
        """Wire block connections (called once before simulation)."""
{connection_code}

    def step(self, t: float, dt: float, kpass: int):
        """Execute one simulation step.

        Args:
            t: Current simulation time
            dt: Time step
            kpass: Integration pass number (0 to num_passes-1)
        """
        # Wire connections (update inputs from outputs)
        self.wire_connections()

        # Update all blocks in execution order
{chr(10).join(update_calls)}


def run_simulation(
    model: Model,
    dt: float = {config.step_size},
    t_start: float = {config.start_time},
    t_end: float = {config.stop_time},
    method: str = "{config.integration_method.value}",
) -> dict:
    """Run the simulation.

    Args:
        model: Model instance
        dt: Time step
        t_start: Start time
        t_end: Stop time
        method: Integration method (euler, rk2, rk4, merson)

    Returns:
        Dictionary of results with 'time' and output signals
    """
    # Initialize model
    model.init()

    # Get integration function
    propagate = get_propagate_function(method)
    num_passes = get_num_passes(method)

    # Results storage
    results = {{'time': []}}
{output_recording['init']}

    # Simulation loop
    t = t_start
    while t <= t_end:
        # Record outputs before stepping
        results['time'].append(t)
{output_recording['record']}

        # Integration passes
        for kpass in range(num_passes):
            model.step(t, dt, kpass)
            propagate(model._integrators, dt, kpass)

        t += dt

    return results
'''

    def _generate_connection_code(self, model_info: CompiledModelInfo) -> str:
        """Generate connection wiring code."""
        lines = []
        for block in model_info.blocks:
            var_name = self.get_block_var_name(block)
            for i, conn in enumerate(block.input_connections):
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next(
                    (b for b in model_info.blocks if b.id == source_id), None
                )
                if source_block:
                    source_var = self.get_block_var_name(source_block)
                    if target_port is not None and target_port > 0:
                        lines.append(
                            f"        self.{var_name}.input{target_port} = "
                            f"self.{source_var}.get_output({source_port})"
                        )
                    else:
                        lines.append(
                            f"        self.{var_name}.input = "
                            f"self.{source_var}.get_output({source_port})"
                        )

        return "\n".join(lines) if lines else "        pass"

    def _generate_output_recording(self, model_info: CompiledModelInfo) -> dict:
        """Generate output recording code."""
        init_lines = []
        record_lines = []

        for block_id in model_info.sink_blocks:
            block = next((b for b in model_info.blocks if b.id == block_id), None)
            if block:
                var_name = self.get_block_var_name(block)
                signal_name = self.sanitize_identifier(block.name or block.id)
                init_lines.append(f"    results['{signal_name}'] = []")
                record_lines.append(
                    f"        results['{signal_name}'].append("
                    f"model.{var_name}.get_output())"
                )

        return {
            'init': "\n".join(init_lines) if init_lines else "    pass",
            'record': "\n".join(record_lines) if record_lines else "        pass",
        }

    def _generate_requirements(self) -> str:
        """Generate requirements.txt."""
        return """numpy>=1.20.0
"""

    def _generate_setup(self, config: Any) -> str:
        """Generate setup.py."""
        return f'''"""Package setup."""

from setuptools import setup, find_packages

setup(
    name="{config.project_name}",
    version="1.0.0",
    description="Simulation generated by LibreSim Coder",
    py_modules=["simulation", "blocks", "integration"],
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.20.0",
    ],
    entry_points={{
        "console_scripts": [
            "{config.project_name}=main:main",
        ],
    }},
)
'''

    def _generate_readme(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate README.md."""
        return f'''# {config.project_name}

Simulation generated by LibreSim Coder.

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run simulation
python main.py
```

## Model Information

- **Blocks**: {len(model_info.blocks)}
- **Integration Method**: {config.integration_method.value}
- **Step Size**: {config.step_size}
- **Duration**: {config.start_time} to {config.stop_time} seconds

## Files

- `simulation.py` - Model class and run_simulation() function
- `blocks.py` - Block class definitions
- `integration.py` - Numerical integration methods
- `main.py` - Example runner (outputs to results.csv)

## Usage

```python
from simulation import Model, run_simulation

# Create and run model
model = Model()
results = run_simulation(model, dt=0.01, t_end=10.0)

# Access results
print(results['time'])  # Time vector
```
'''
