"""Python code generator."""

from typing import Any

from ...integration import IntegrationCodeGenerator
from ...models import (
    BlockInfo,
    CompiledModelInfo,
    GeneratedProject,
    IntegrationMethod,
    Language,
)
from ..base import LanguageGenerator
from .blocks import BLOCK_TEMPLATES, get_block_template


class PythonCodeGenerator(LanguageGenerator):
    """Generate Python simulation code."""

    def generate(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> GeneratedProject:
        """Generate a complete Python project."""
        project = GeneratedProject(
            name=config.project_name,
            language=Language.PYTHON,
        )

        # Generate blocks.py - all block class definitions
        blocks_code = self._generate_blocks_file(model_info)
        project.add_file("blocks.py", blocks_code)

        # Generate integration.py - integration methods
        integration_code = self.generate_integration_code(config.integration_method)
        project.add_file("integration.py", integration_code)

        # Generate simulation.py - main model class and step function
        simulation_code = self._generate_simulation_file(model_info, config)
        project.add_file("simulation.py", simulation_code)

        # Generate main.py - example runner
        if config.include_main:
            main_code = self.generate_main_code(model_info, config)
            project.add_file("main.py", main_code)

        # Generate requirements.txt
        requirements = self._generate_requirements()
        project.add_file("requirements.txt", requirements)

        # Generate setup.py
        setup_code = self._generate_setup(config)
        project.add_file("setup.py", setup_code)

        # Generate README.md
        readme = self._generate_readme(model_info, config)
        project.add_file("README.md", readme)

        # Generate Dockerfile for compilation
        dockerfile = self._generate_dockerfile(config)
        project.add_file("Dockerfile", dockerfile)

        # Generate docker build and run scripts
        build_script = self._generate_build_script(config)
        project.add_file("build.sh", build_script)
        run_script = self._generate_run_script(config)
        project.add_file("run.sh", run_script)

        # Validate generated Python code
        self._validate_python_code(project)

        return project

    def _validate_python_code(self, project: GeneratedProject) -> None:
        """Validate that generated Python code has no syntax errors.

        Raises:
            SyntaxError: If any Python file has syntax errors
        """
        for file in project.files:
            if file.path.endswith(".py"):
                try:
                    compile(file.content, file.path, "exec")
                except SyntaxError as e:
                    # Add more context to the error
                    error_msg = (
                        f"Syntax error in generated {file.path}:\n"
                        f"  Line {e.lineno}: {e.text.strip() if e.text else '(no text)'}\n"
                        f"  Error: {e.msg}"
                    )
                    # Re-raise with better message
                    raise SyntaxError(error_msg) from e

    def generate_block_code(self, block: BlockInfo) -> str:
        """Generate code for a single block."""
        template_fn = get_block_template(block.type)
        if template_fn is None:
            # Fallback to passthrough
            return self._generate_passthrough_block(block)

        # Call template function with block and class name
        class_name = f"Block_{self.sanitize_identifier(block.id)}"
        return template_fn(block, class_name)

    def generate_integration_code(self, method: IntegrationMethod) -> str:
        """Generate integration method code."""
        return f'''"""Integration methods for numerical simulation."""

{IntegrationCodeGenerator.generate_python_all()}
'''

    def generate_main_code(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate main entry point code."""
        csv_output = ""
        if config.include_csv_output:
            csv_output = """
    # Write results to CSV
    with open('results.csv', 'w', newline='') as f:
        import csv
        writer = csv.writer(f)

        # Header
        header = ['time'] + list(results.keys())
        header.remove('time')
        writer.writerow(['time'] + [k for k in results.keys() if k != 'time'])

        # Data rows
        n_points = len(results['time'])
        for i in range(n_points):
            row = [results['time'][i]]
            for key in results:
                if key != 'time':
                    row.append(results[key][i])
            writer.writerow(row)

    print(f"Results written to results.csv ({n_points} data points)")
"""

        return f'''#!/usr/bin/env python3
"""Example simulation runner.

Generated by LibreSim Coder.
"""

from simulation import Model, run_simulation


def main():
    """Run the simulation and output results."""
    # Create model instance
    model = Model()

    # Run simulation
    print("Running simulation...")
    results = run_simulation(
        model,
        dt={config.step_size},
        t_end={config.stop_time},
        t_start={config.start_time},
        method="{config.integration_method.value}",
    )

    print(f"Simulation complete. {{len(results['time'])}} time steps.")
{csv_output}

if __name__ == "__main__":
    main()
'''

    def _generate_blocks_file(self, model_info: CompiledModelInfo) -> str:
        """Generate blocks.py with all block class definitions."""
        imports = '''"""Block class definitions.

Generated by LibreSim Coder.
"""

import math
from typing import Any, List, Optional

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False

'''
        classes = []

        # Generate a class for each block in the model
        for block in model_info.blocks:
            class_code = self._generate_block_class(block)
            classes.append(class_code)

        return imports + "\n\n".join(classes)

    def _generate_block_class(self, block: BlockInfo) -> str:
        """Generate a Python class for a block."""
        class_name = f"Block_{self.sanitize_identifier(block.id)}"
        self.get_block_var_name(block)

        # Get template for this block type
        template_func = BLOCK_TEMPLATES.get(block.type)
        if template_func:
            return template_func(block, class_name)

        # Default passthrough implementation
        return self._generate_passthrough_block(block)

    def _generate_passthrough_block(self, block: BlockInfo) -> str:
        """Generate a passthrough block (for unsupported types)."""
        class_name = f"Block_{self.sanitize_identifier(block.id)}"
        # Check if block has vector output dimensions
        has_vector_output = (
            block.output_dimensions
            and len(block.output_dimensions) > 0
            and len(block.output_dimensions[0]) > 0
            and block.output_dimensions[0][0] > 1
        )
        has_vector_input = (
            block.input_dimensions
            and len(block.input_dimensions) > 0
            and len(block.input_dimensions[0]) > 0
            and block.input_dimensions[0][0] > 1
        )

        if has_vector_output or has_vector_input:
            output_size = (
                block.output_dimensions[0][0]
                if has_vector_output
                else (block.input_dimensions[0][0] if has_vector_input else 1)
            )
            input_size = block.input_dimensions[0][0] if has_vector_input else 1
            return f'''
class {class_name}:
    """Passthrough block (vector): {block.name} (type: {block.type})"""

    def __init__(self):
        self.input = [0.0] * {input_size}
        self.output = [0.0] * {output_size}

    def init(self):
        self.output = [0.0] * {output_size}

    def update(self, t: float):
        # Passthrough: copy input to output (truncate/pad if sizes differ)
        if isinstance(self.input, (list, tuple)):
            for i in range(min(len(self.input), len(self.output))):
                self.output[i] = self.input[i]
        else:
            self.output[0] = self.input

    def get_output(self, port: int = 0) -> float:
        if port < len(self.output):
            return self.output[port]
        return 0.0

    def get_output_vector(self) -> list:
        return list(self.output)
'''
        else:
            return f'''
class {class_name}:
    """Passthrough block: {block.name} (type: {block.type})"""

    def __init__(self):
        self.input = 0.0
        self.output = 0.0

    def init(self):
        self.output = 0.0

    def update(self, t: float):
        self.output = self.input

    def get_output(self, port: int = 0) -> float:
        return self.output

    def get_output_vector(self) -> list:
        if isinstance(self.output, (list, tuple)):
            return list(self.output)
        return [self.output]
'''

    def _generate_simulation_file(
        self,
        model_info: CompiledModelInfo,
        config: Any,
    ) -> str:
        """Generate simulation.py with Model class and run function."""
        # Build block instantiation code
        block_inits = []
        for block in model_info.blocks:
            class_name = f"Block_{self.sanitize_identifier(block.id)}"
            var_name = self.get_block_var_name(block)
            block_inits.append(f"        self.{var_name} = {class_name}()")

        # Build connection wiring code (for wire_connections method)
        connection_code = self._generate_connection_code(model_info)

        # Build per-block wiring map (for inline wiring during step)
        block_wiring = self._generate_per_block_wiring(model_info)

        # Build update order code (8 spaces - inside method body)
        # Each block has its inputs wired from upstream outputs, then updates
        update_calls: list[str] = []
        for block_id in model_info.execution_order:
            block_match = next((b for b in model_info.blocks if b.id == block_id), None)
            if block_match is not None:
                var_name = self.get_block_var_name(block_match)
                # Add wiring for this block's inputs (if any)
                if block_id in block_wiring:
                    for wire_line in block_wiring[block_id]:
                        update_calls.append(wire_line)
                update_calls.append(f"        self.{var_name}.update(t)")

        # Build integrator list for state propagation
        integrator_list: list[str] = []
        multi_state_list: list[str] = []  # Blocks with propagate_states method
        for block_id in model_info.integrator_blocks:
            block_match = next((b for b in model_info.blocks if b.id == block_id), None)
            if block_match is not None:
                var_name = self.get_block_var_name(block_match)
                integrator_list.append(f"self.{var_name}")
                # Multi-state blocks need additional propagation
                if block_match.type in (
                    "transfer_function",
                    "state_space",
                    "second_order",
                    "pid_controller",
                ):
                    multi_state_list.append(f"self.{var_name}")

        # Build output recording code
        output_recording = self._generate_output_recording(model_info)

        # Generate multi-state propagation code (if any)
        multi_state_propagation = ""
        if multi_state_list:
            multi_state_propagation = """
            # Propagate multi-state blocks (transfer functions, state-space)
            for block in model._multi_state_blocks:
                if hasattr(block, 'propagate_states'):
                    block.propagate_states(dt, kpass)"""

        return f'''"""Simulation model.

Generated by LibreSim Coder.
"""

from blocks import *
from integration import get_propagate_function, get_num_passes, get_stage_offsets


class Model:
    """Simulation model containing all blocks and connections."""

    def __init__(self):
        # Instantiate all blocks
{chr(10).join(block_inits)}

        # List of integrator blocks for state propagation
        self._integrators = [{", ".join(integrator_list)}]

        # List of multi-state blocks needing additional propagation
        self._multi_state_blocks = [{", ".join(multi_state_list)}]

    def init(self):
        """Initialize all blocks."""
        for block in self._get_all_blocks():
            if hasattr(block, 'init'):
                block.init()

    def _get_all_blocks(self):
        """Get list of all block instances."""
        return [getattr(self, attr) for attr in dir(self)
                if attr.startswith('block_') and not callable(getattr(self, attr))]

    def wire_connections(self):
        """Wire block connections (called once before simulation)."""
{connection_code}

    def step(self, t: float, dt: float, kpass: int):
        """Execute one simulation step.

        Args:
            t: Current simulation time
            dt: Time step
            kpass: Integration pass number (0 to num_passes-1)
        """
        # Update all blocks in execution order
        # Each block wires its inputs from upstream outputs, then updates
{chr(10).join(update_calls)}


def run_simulation(
    model: Model,
    dt: float = {config.step_size},
    t_start: float = {config.start_time},
    t_end: float = {config.stop_time},
    method: str = "{config.integration_method.value}",
) -> dict:
    """Run the simulation.

    Args:
        model: Model instance
        dt: Time step
        t_start: Start time
        t_end: Stop time
        method: Integration method (euler, rk2, rk4, merson)

    Returns:
        Dictionary of results with 'time' and output signals
    """
    # Initialize model
    model.init()

    # Get integration function
    propagate = get_propagate_function(method)
    num_passes = get_num_passes(method)
    stage_offsets = get_stage_offsets(method)

    # Results storage
    results = {{'time': []}}
{output_recording["init"]}

    # Simulation loop
    # OSK reports outputs after update() but BEFORE propagation for kpass=0
    # This captures the state at the current time before integration advances it
    t = t_start
    while t <= t_end:
        # Integration passes
        for kpass in range(num_passes):
            model.step(t + stage_offsets[kpass] * dt, dt, kpass)

            # Record outputs after kpass=0 update, before propagation (matches OSK)
            if kpass == 0:
                results['time'].append(t)
{output_recording["record"]}

            propagate(model._integrators, dt, kpass){multi_state_propagation}

        t += dt

    return results
'''

    # Block types that use indexed inputs (input0, input1, etc.)
    MULTI_INPUT_BLOCKS = {"sum", "product", "mux", "switch"}

    # Block types that output vectors and have get_output_vector() method
    VECTOR_OUTPUT_BLOCKS = {"mux", "constant", "gain"}

    # Block types that expect vector inputs (not via indexed ports)
    VECTOR_INPUT_BLOCKS = {"demux", "gain"}

    def _is_vector_output(self, block: BlockInfo, port: int = 0) -> bool:
        """Check if a block's output port produces a vector (not scalar)."""
        # Check output dimensions from model
        if block.output_dimensions and port < len(block.output_dimensions):
            dims = block.output_dimensions[port]
            # [1] is scalar, anything else is vector
            if len(dims) > 0 and dims[0] > 1:
                return True
        # Also check if block type is known to output vectors
        if block.type in self.VECTOR_OUTPUT_BLOCKS:
            # For mux, always outputs vector
            if block.type == "mux":
                return True
            # For constant, check if value is a list
            if block.type == "constant":
                value = block.parameters.get("value", 0.0)
                return isinstance(value, (list, tuple))
            # Gain outputs vector if input dimensions say so
            # (handled by output_dimensions check above)
        return False

    def _expects_vector_input(self, block: BlockInfo, port: int = 0) -> bool:
        """Check if a block expects a vector input (not scalar) at given port."""
        # Check input dimensions from model
        if block.input_dimensions and port < len(block.input_dimensions):
            dims = block.input_dimensions[port]
            if len(dims) > 0 and dims[0] > 1:
                return True
        # Demux always expects vector input
        if block.type == "demux":
            return True
        return False

    def _generate_connection_code(self, model_info: CompiledModelInfo) -> str:
        """Generate connection wiring code."""
        lines = []
        for block in model_info.blocks:
            var_name = self.get_block_var_name(block)
            for _i, conn in enumerate(block.input_connections):
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next((b for b in model_info.blocks if b.id == source_id), None)
                if source_block:
                    source_var = self.get_block_var_name(source_block)

                    # Determine target port index
                    port_idx = target_port if target_port is not None else 0

                    # Check if this is a vector-to-vector connection
                    source_is_vector = self._is_vector_output(source_block, source_port)
                    target_expects_vector = self._expects_vector_input(block, port_idx)

                    # Multi-input blocks use input0, input1, etc. for scalar inputs
                    if block.type in self.MULTI_INPUT_BLOCKS:
                        lines.append(
                            f"        self.{var_name}.input{port_idx} = "
                            f"self.{source_var}.get_output({source_port})"
                        )
                    elif source_is_vector and target_expects_vector:
                        # Vector-to-vector: use get_output_vector()
                        # For port 0 use 'input', for port 1+ use 'input1', 'input2', etc.
                        input_field = "input" if port_idx == 0 else f"input{port_idx}"
                        lines.append(
                            f"        self.{var_name}.{input_field} = "
                            f"self.{source_var}.get_output_vector()"
                        )
                    elif target_port is not None and target_port > 0:
                        lines.append(
                            f"        self.{var_name}.input{target_port} = "
                            f"self.{source_var}.get_output({source_port})"
                        )
                    else:
                        lines.append(
                            f"        self.{var_name}.input = "
                            f"self.{source_var}.get_output({source_port})"
                        )

        return "\n".join(lines) if lines else "        pass"

    def _generate_per_block_wiring(self, model_info: CompiledModelInfo) -> dict[str, list[str]]:
        """Generate per-block wiring code for inline wiring during step.

        Returns:
            Dictionary mapping block_id to list of wiring code lines
        """
        wiring: dict[str, list[str]] = {}
        for block in model_info.blocks:
            var_name = self.get_block_var_name(block)
            block_lines = []
            for conn in block.input_connections:
                source_id, source_port, target_port = self.parse_connection(conn)
                source_block = next((b for b in model_info.blocks if b.id == source_id), None)
                if source_block:
                    source_var = self.get_block_var_name(source_block)

                    # Determine target port index
                    port_idx = target_port if target_port is not None else 0

                    # Check if this is a vector-to-vector connection
                    source_is_vector = self._is_vector_output(source_block, source_port)
                    target_expects_vector = self._expects_vector_input(block, port_idx)

                    # Multi-input blocks use input0, input1, etc.
                    if block.type in self.MULTI_INPUT_BLOCKS:
                        block_lines.append(
                            f"        self.{var_name}.input{port_idx} = "
                            f"self.{source_var}.get_output({source_port})"
                        )
                    elif source_is_vector and target_expects_vector:
                        # Vector-to-vector: use get_output_vector()
                        # For port 0 use 'input', for port 1+ use 'input1', 'input2', etc.
                        input_field = "input" if port_idx == 0 else f"input{port_idx}"
                        block_lines.append(
                            f"        self.{var_name}.{input_field} = "
                            f"self.{source_var}.get_output_vector()"
                        )
                    elif target_port is not None and target_port > 0:
                        block_lines.append(
                            f"        self.{var_name}.input{target_port} = "
                            f"self.{source_var}.get_output({source_port})"
                        )
                    else:
                        block_lines.append(
                            f"        self.{var_name}.input = "
                            f"self.{source_var}.get_output({source_port})"
                        )
            if block_lines:
                wiring[block.id] = block_lines
        return wiring

    def _generate_output_recording(self, model_info: CompiledModelInfo) -> dict:
        """Generate output recording code from the shared canonical output schema."""
        init_lines: list[str] = []
        record_lines: list[str] = []
        blocks = {block.id: block for block in model_info.blocks}

        for signal in model_info.output_signals:
            source = blocks[signal.source_block_id]
            var_name = self.get_block_var_name(source)
            port = signal.flat_index if signal.dimensions[0] > 1 else signal.source_output_port
            init_lines.append(f"    results['{signal.canonical_key}'] = []")
            record_lines.append(
                f"                results['{signal.canonical_key}'].append("
                f"model.{var_name}.get_output({port}))"
            )

        return {
            "init": "\n".join(init_lines) if init_lines else "    pass",
            "record": "\n".join(record_lines) if record_lines else "                pass",
        }

    def _generate_requirements(self) -> str:
        """Generate requirements.txt."""
        return """numpy>=1.20.0
"""

    def _generate_setup(self, config: Any) -> str:
        """Generate setup.py."""
        return f'''"""Package setup."""

from setuptools import setup, find_packages

setup(
    name="{config.project_name}",
    version="1.0.0",
    description="Simulation generated by LibreSim Coder",
    py_modules=["simulation", "blocks", "integration"],
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.20.0",
    ],
    entry_points={{
        "console_scripts": [
            "{config.project_name}=main:main",
        ],
    }},
)
'''

    def _generate_readme(self, model_info: CompiledModelInfo, config: Any) -> str:
        """Generate README.md."""
        return f"""# {config.project_name}

Simulation generated by LibreSim Coder.

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run simulation
python main.py
```

## Model Information

- **Blocks**: {len(model_info.blocks)}
- **Integration Method**: {config.integration_method.value}
- **Step Size**: {config.step_size}
- **Duration**: {config.start_time} to {config.stop_time} seconds

## Files

- `simulation.py` - Model class and run_simulation() function
- `blocks.py` - Block class definitions
- `integration.py` - Numerical integration methods
- `main.py` - Example runner (outputs to results.csv)

## Usage

```python
from simulation import Model, run_simulation

# Create and run model
model = Model()
results = run_simulation(model, dt=0.01, t_end=10.0)

# Access results
print(results['time'])  # Time vector
```

## Docker Build

To create a standalone executable using Docker:

```bash
# Build the Docker image and compile
./build.sh

# Or manually:
docker build -t {config.project_name}-builder .
docker run --rm -v $(pwd)/output:/output {config.project_name}-builder
```

The executable will be created in the `output/` directory.
"""

    def _generate_dockerfile(self, config: Any) -> str:
        """Generate Dockerfile for compilation and execution."""
        return f"""# Dockerfile for compiling and running {config.project_name}
# Generated by LibreSim Coder

FROM python:3.11-slim

LABEL maintainer="LibreSim Coder"
LABEL description="Build environment for {config.project_name}"

# Install system dependencies (binutils required for PyInstaller on Linux)
RUN apt-get update && apt-get install -y --no-install-recommends \\
    binutils \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir numpy pyinstaller

# Set working directory
WORKDIR /build

# Copy project files
COPY . /build/

# Make scripts executable
RUN chmod +x /build/run.sh

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Build executable
RUN pyinstaller \\
    --onefile \\
    --distpath /output-build \\
    --workpath /tmp/pyinstaller \\
    --specpath /tmp/pyinstaller \\
    --name {config.project_name} \\
    main.py

# Default command runs the simulation and copies outputs
CMD ["/build/run.sh"]
"""

    def _generate_build_script(self, config: Any) -> str:
        """Generate build script."""
        return f"""#!/bin/bash
# Build and run script for {config.project_name}
# Generated by LibreSim Coder
#
# This script:
# 1. Builds a Docker image with the compiled simulation
# 2. Runs the simulation inside the container
# 3. Copies the executable and results to ./output/

set -e

PROJECT_NAME="{config.project_name}"
IMAGE_NAME="${{PROJECT_NAME}}-builder"

echo "=== Building and Running $PROJECT_NAME (Python) ==="

# Create output directory
mkdir -p output

# Get absolute path (works on both Linux/Mac and Windows Git Bash)
if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ -n "$WINDIR" ]]; then
    # Windows: convert to Docker-compatible path
    OUTPUT_PATH="$(cd output && pwd -W 2>/dev/null || pwd)"
else
    OUTPUT_PATH="$(cd output && pwd)"
fi

# Build Docker image (compiles the code)
echo "[1/2] Building Docker image (compiling code)..."
docker build -t "$IMAGE_NAME" .

# Run container (executes simulation and copies outputs)
echo "[2/2] Running simulation..."
# MSYS_NO_PATHCONV prevents Git Bash from mangling the volume mount path
MSYS_NO_PATHCONV=1 docker run --rm -v "$OUTPUT_PATH:/output" "$IMAGE_NAME"

echo ""
echo "=== Complete ==="
echo "Output files:"
ls -la output/

# Show first/last few lines of results if CSV exists
if [ -f output/results.csv ]; then
    echo ""
    echo "=== Results Preview (first 5 lines) ==="
    head -n 5 output/results.csv
    echo "..."
    echo "=== Results Preview (last 5 lines) ==="
    tail -n 5 output/results.csv
fi
"""

    def _generate_run_script(self, config: Any) -> str:
        """Generate run script that executes inside Docker container."""
        return f"""#!/bin/bash
# Run script for {config.project_name}
# This script runs inside the Docker container
# Generated by LibreSim Coder

set -e

echo "Running simulation..."

# Run the simulation (generates results.csv in current directory)
cd /output-build
./{config.project_name}

echo ""
echo "Simulation complete."

# Copy outputs to mounted volume
if [ -d "/output" ]; then
    echo "Copying outputs to /output..."
    cp -f {config.project_name} /output/ 2>/dev/null || true
    cp -f results.csv /output/ 2>/dev/null || true
    echo "Done."
else
    echo "Warning: /output not mounted, results not copied."
fi
"""
