"""OSK Block implementations for LibreSim.

This package contains simulation block implementations that use
the OSK (Object-oriented Simulation Kernel) framework.
"""

from .aerospace import (
    DCMToQuaternion,
    EulerToQuaternion,
    FlatEarthGravity,
    ISAAtmosphere,
    QuaternionConjugate,
    QuaternionMultiply,
    QuaternionNormalize,
    QuaternionRotateVector,
    QuaternionToDCM,
    QuaternionToEuler,
    SixDOFEuler,
    WGS84Gravity,
)
from .continuous import (
    Derivative,
    Integrator,
    LimitedIntegrator,
    PIDController,
    SecondOrder,
    StateSpace,
    TransferFunction,
    TransportDelay,
    ZeroPole,
)
from .control_analysis import BodePlot, NyquistPlot, PoleZeroMap, StepInfo
from .control_design import (
    AntiWindupPID,
    LeadLagCompensator,
    LQRController,
    ModelReference,
    PDController,
    PIController,
    PolePlacement,
)
from .data_types import (
    ComplexToRealImag,
    DataTypeConversion,
    RealImagToComplex,
)
from .discrete import (
    DiscreteDerivative,
    DiscreteIntegrator,
    DiscretePIDController,
    DiscreteStateSpace,
    DiscreteTransferFunction,
    FirstOrderHold,
    Memory,
    UnitDelay,
    ZeroOrderHold,
)
from .dsp import (
    FFT,
    IFFT,
    RMS,
    Convolution,
    Downsampler,
    FIRFilter,
    IIRFilter,
    Interpolator,
    Mean,
    PeakDetector,
    Upsampler,
    Variance,
    WindowFunction,
    ZeroCrossingDetector,
)
from .logic import (
    BitOperator,
    CompareToConstant,
    CompareToZero,
    LogicalOperator,
    RelationalOperator,
)
from .math_ops import (
    Abs,
    Atan2,
    Bias,
    ComplexToMagnitudeAngle,
    CrossProduct,
    DeadZone,
    Demux,
    Divide,
    DotProduct,
    Exp,
    Gain,
    Hypot,
    Log,
    Log10,
    MagnitudeAngle,
    MathFunction,
    MinMax,
    Mod,
    Mux,
    Polynomial,
    Power,
    Product,
    Reciprocal,
    Reshape,
    Rounding,
    Saturation,
    Sign,
    SliderGain,
    Sqrt,
    Square,
    Sum,
    Switch,
    Trigonometry,
    UnaryMinus,
    WeightedSum,
)
from .matrix_ops import (
    Assignment,
    Concatenate,
    MatrixInverse,
    MatrixMultiply,
    MatrixSum,
    MatrixTranspose,
    Selector,
    VectorNorm,
)
from .navigation import (
    CoordinateTransformationConversion,
    ECEFToLLA,
    ECEFToNED,
    FlatEarthPosition,
    GreatCircleDistance,
    LLAToECEF,
    NEDToECEF,
    WaypointFollower,
)
from .nonlinear import (
    Coulomb,
    HitCrossing,
    Hysteresis,
    LookupTable1D,
    LookupTable2D,
    Quantizer,
    Relay,
    SlewRateLimiter,
    Stiction,
    VariableTransportDelay,
    WrapToRange,
)
from .observers import ExtendedKalmanFilter, KalmanFilter, LuenbergerObserver
from .rf import (
    AMModulator,
    Attenuator,
    FMModulator,
    PhaseNoise,
    RFAmplifier,
    RFBudgetElement,
    RFFilter,
    RFMixer,
    SParameterNetwork,
    WattsTodBm,
    dBmToWatts,
)
from .sensor_fusion import (
    Accelerometer,
    AlphaBetaFilter,
    AlphaBetaGammaFilter,
    Altimeter,
    ComplementaryFilter,
    GPSSensor,
    Gyroscope,
    IMUSensor,
    INSGPSFusion,
    MadgwickFilter,
    Magnetometer,
    MahonyFilter,
)
from .signal_processing import (
    AnalogFilter,
    Backlash,
    BandPassFilter,
    HighPassFilter,
    LowPassFilter,
    MovingAverage,
    NotchFilter,
    RateLimiter,
)
from .sinks import Scope, ToWorkspace
from .sources import (
    BandLimitedWhiteNoise,
    ChirpSignal,
    Clock,
    Constant,
    FromWorkspace,
    Ground,
    PulseGenerator,
    Ramp,
    RepeatingSequence,
    SignalGenerator,
    SineWave,
    Step,
    UniformNoise,
    WhiteNoise,
)
from .subsystems import Inport, Outport, Subsystem

__all__ = [
    # Sources
    "Constant",
    "Step",
    "Ramp",
    "SineWave",
    "Clock",
    "PulseGenerator",
    "WhiteNoise",
    "UniformNoise",
    "RepeatingSequence",
    "ChirpSignal",
    "BandLimitedWhiteNoise",
    "Ground",
    "FromWorkspace",
    "SignalGenerator",
    # Sinks
    "Scope",
    "ToWorkspace",
    # Continuous
    "Integrator",
    "Derivative",
    "TransferFunction",
    "StateSpace",
    "PIDController",
    "TransportDelay",
    "SecondOrder",
    "LimitedIntegrator",
    "ZeroPole",
    # Discrete
    "UnitDelay",
    "ZeroOrderHold",
    "DiscreteIntegrator",
    "DiscreteDerivative",
    "DiscreteTransferFunction",
    "Memory",
    "DiscreteStateSpace",
    "FirstOrderHold",
    "DiscretePIDController",
    # Math
    "Sum",
    "Gain",
    "Product",
    "Abs",
    "Bias",
    "Saturation",
    "Switch",
    "Mux",
    "Demux",
    "MathFunction",
    "Trigonometry",
    "Sign",
    "DeadZone",
    "Reshape",
    "Divide",
    "Mod",
    "Atan2",
    "Rounding",
    "MinMax",
    "DotProduct",
    "CrossProduct",
    "Hypot",
    "UnaryMinus",
    "SliderGain",
    "WeightedSum",
    "Polynomial",
    "MagnitudeAngle",
    "ComplexToMagnitudeAngle",
    "Sqrt",
    "Reciprocal",
    "Square",
    "Power",
    "Exp",
    "Log",
    "Log10",
    # Logic
    "CompareToZero",
    "CompareToConstant",
    "RelationalOperator",
    "LogicalOperator",
    "BitOperator",
    # Subsystems
    "Inport",
    "Outport",
    "Subsystem",
    # Signal Processing
    "RateLimiter",
    "MovingAverage",
    "LowPassFilter",
    "HighPassFilter",
    "BandPassFilter",
    "AnalogFilter",
    "NotchFilter",
    "Backlash",
    # Nonlinear
    "LookupTable1D",
    "LookupTable2D",
    "Quantizer",
    "Relay",
    "Coulomb",
    "VariableTransportDelay",
    "WrapToRange",
    "HitCrossing",
    "Hysteresis",
    "Stiction",
    "SlewRateLimiter",
    # Observers
    "LuenbergerObserver",
    "KalmanFilter",
    "ExtendedKalmanFilter",
    # Control Analysis
    "BodePlot",
    "NyquistPlot",
    "PoleZeroMap",
    "StepInfo",
    # Data Types
    "DataTypeConversion",
    "RealImagToComplex",
    "ComplexToRealImag",
    # Matrix Operations
    "MatrixMultiply",
    "MatrixTranspose",
    "MatrixInverse",
    "Selector",
    "Assignment",
    "Concatenate",
    "MatrixSum",
    "VectorNorm",
    # Control Design
    "LQRController",
    "PolePlacement",
    "LeadLagCompensator",
    "PIController",
    "PDController",
    "AntiWindupPID",
    "ModelReference",
    # Aerospace
    "QuaternionNormalize",
    "QuaternionMultiply",
    "QuaternionConjugate",
    "QuaternionToEuler",
    "EulerToQuaternion",
    "QuaternionRotateVector",
    "DCMToQuaternion",
    "QuaternionToDCM",
    "ISAAtmosphere",
    "SixDOFEuler",
    "FlatEarthGravity",
    "WGS84Gravity",
    # DSP
    "FFT",
    "IFFT",
    "FIRFilter",
    "IIRFilter",
    "Convolution",
    "Downsampler",
    "Upsampler",
    "Interpolator",
    "WindowFunction",
    "Mean",
    "Variance",
    "RMS",
    "PeakDetector",
    "ZeroCrossingDetector",
    # RF
    "RFAmplifier",
    "RFMixer",
    "RFFilter",
    "SParameterNetwork",
    "RFBudgetElement",
    "Attenuator",
    "AMModulator",
    "FMModulator",
    "PhaseNoise",
    "dBmToWatts",
    "WattsTodBm",
    # Navigation
    "CoordinateTransformationConversion",
    "LLAToECEF",
    "ECEFToLLA",
    "ECEFToNED",
    "NEDToECEF",
    "WaypointFollower",
    "GreatCircleDistance",
    "FlatEarthPosition",
    # Sensor Fusion
    "IMUSensor",
    "Accelerometer",
    "Gyroscope",
    "Magnetometer",
    "GPSSensor",
    "Altimeter",
    "ComplementaryFilter",
    "MadgwickFilter",
    "MahonyFilter",
    "INSGPSFusion",
    "AlphaBetaFilter",
    "AlphaBetaGammaFilter",
]
